let sp1 = {
    masp: 1,
    tensp: 'iPhone 13 256GB | Chính hãng VN/A',
    tensp1: 'iPhone 13 256GB | Chính hãng VN/A',
    tensp2: 'iPhone 13 256GB | Chính hãng VN/A',
    hinhanh: '../images/ChiTietiPhone/iphone_Blue_1.png',
    hinhanh1: '../images/ChiTietiPhone/iphone_Blue_2.png',
    hinhanh2: '../images/ChiTietiPhone/iphone_Blue_3.png',
    hinhanh3: '../images/ChiTietiPhone/iphone_Blue_1.png',
    hinhanh4: '../images/ChiTietiPhone/iphone_Blue_2.png',
    hinhanh5: '../images/ChiTietiPhone/iphone_Blue_3.png',
    hinhanh6: '../images/ChiTietiPhone/iphone13_256GB-removebg-preview.png',
    soDanhGia: "1 đánh giá",
    loaiPhienBan: "256 GB",
    giaHienTai: "19.990.000đ",
    giaHienTai1: "19.990.000đ",
    giaGiam: "21.990.000đ",
    mauSac: "Xanh dương",
    kichThuocManHinh: '6.1"',
    kichThuocManHinh1: '6.1"',
    congNgheManHinh: 'Super Retina XDR OLED',
    congNgheManHinh1: 'Super Retina XDR OLED',
    dungLuongRam: "4 GB",
    dungLuongRam1: "4 GB",
    boNhoTrong: '256 GB',
    boNhoTrong1: '256 GB',
    pin: '3240 mAh',
    pin1: '3240 mAh',
    heDieuHanh: "iOS 15",
    heDieuHanh1: "iOS 15",
    doPhanGiaiManHinh: '2532 x 1170 pixels',
    tanSoQuet: '60Hz',
    kieuManHinh: 'Tai thỏ',
    cameraSau: 'Camera góc rộng: 12MP, f/1.6\nCamera góc siêu rộng: 12MP, ƒ/2.4\nQuay video 4K 2160p@24fps/30fps/60fps\nFullHD 1080p@30fps/60fps/240fps\nHD 720p@30fps',
    cameraTruoc: '12MP, f/2.2',
    loaiCPU: '3.22 GHz',
    chipsetVaGPU: 'GPU',
    chip: 'Apple GPU 4 nhân',
    congNgheSac: 'Sạc nhanh 20W, Sạc không dây, Sạc ngược không dây 15W, Sạc pin nhanh, Tiết kiệm pin',
    theSim: '2 SIM (nano SIM và eSIM)',
    hoTroMang: '5G',
    wifi: 'Wi Fi 6 (802.11ax)',
    kichThuoc: '146,7 x 71,5 x 7,65mm',
    trongLuong: '174g',
    chatLieuMatLung: 'Kính',
    chatLieuKhungVien: 'Nhôm'
}


let sp2 = {
    masp: 2,
    tensp: 'iPhone 15 128GB | Chính hãng VN/A',
    tensp1: 'iPhone 15 128GB | Chính hãng VN/A',
    tensp2: 'iPhone 15 128GB | Chính hãng VN/A',
    hinhanh: '../images/ChiTietiPhone/IpPink_1.jpg',
    hinhanh1: '../images/ChiTietiPhone/IpPink_2.jpg',
    hinhanh2: '../images/ChiTietiPhone/IpPink_3.jpg',
    hinhanh3: '../images/ChiTietiPhone/IpPink_1.jpg',
    hinhanh4: '../images/ChiTietiPhone/IpPink_2.jpg',
    hinhanh5: '../images/ChiTietiPhone/IpPink_3.jpg',
    hinhanh6: '../images/ChiTietiPhone/IpPinkBig_1.png',
    soDanhGia: "8 đánh giá",
    loaiPhienBan: "128 GB",
    giaHienTai: "19.790.000đ",
    giaHienTai1: "19.790.000đ",
    giaGiam: "22.990.000đ",
    mauSac: "Hồng",
    kichThuocManHinh: '6.1"',
    kichThuocManHinh1: '6.1"',
    congNgheManHinh: "Super Retina XDR OLED",
    congNgheManHinh1: "Super Retina XDR OLED",
    dungLuongRam: "6 GB",
    dungLuongRam1: "6 GB",
    boNhoTrong: "128 GB",
    boNhoTrong1: "128 GB",
    pin: "3349 mAh",
    pin1: "3349 mAh",
    heDieuHanh: "iOS 17",
    heDieuHanh1: "iOS 17",
    doPhanGiaiManHinh: "2556 x 1179 pixels",
    tanSoQuet: "60Hz",
    kieuManHinh: "Dynamic Island",
    cameraSau: "Chính 48 MP & Phụ 12 MP",
    cameraTruoc: "12MP, ƒ/1.9",
    loaiCPU: "CPU 6 lõi với 2 lõi hiệu năng và 4 lõi tiết kiệm điện",
    chipsetVaGPU: "GPU",
    chip: "5_core GPU",
    congNgheSac: "Hỗ trợ sạc tối đa: 20 W; Sạc pin nhanh; Tiết kiệm pin; Sạc không dây; Sạc không dây MagSafe",
    theSim: "2 SIM (nano_SIM và eSIM)",
    hoTroMang: "5G",
    wifi: "Wi-Fi MIMO; Wi-Fi 6; Wi-Fi 802.11 a/b/g/n/ac/ax",
    kichThuoc: "147.6 x 71.6 x 7.80 mm",
    trongLuong: "171g",
    chatLieuKhungVien: "Kính",
    chatLieuMatLung: "Nhôm",
}


let sp3 = {
    masp: 3,
    tensp: 'iPhone 13 Pro Max 128GB | Chính hãng VN/A',
    tensp1: 'iPhone 13 Pro Max 128GB | Chính hãng VN/A',
    tensp2: 'iPhone 13 Pro Max 128GB | Chính hãng VN/A',
    hinhanh: '../images/ChiTietiPhone/iphone-13-pro-max_1.png',
    hinhanh1: '../images/ChiTietiPhone/iphone-13-pro-max_2.png',
    hinhanh2: '../images/ChiTietiPhone/iphone-13-pro-max_3.png',
    hinhanh3: '../images/ChiTietiPhone/iphone-13-pro-max_1.png',
    hinhanh4: '../images/ChiTietiPhone/iphone-13-pro-max_2.png',
    hinhanh5: '../images/ChiTietiPhone/iphone-13-pro-max_3.png',
    hinhanh6: '../images/ChiTietiPhone/iP13_promax_xam-removebg-preview.png',
    soDanhGia: "52 đánh giá",
    loaiPhienBan: "128 GB",
    giaHienTai: "15.890.000đ",
    giaHienTai1: "15.890.000đ",
    giaGiam: "17.290.000đ",
    mauSac: "Xám",
    kichThuocManHinh: '6.7"',
    kichThuocManHinh1: '6.7"',
    congNgheManHinh: "Super Retina XDR OLED",
    congNgheManHinh1: "Super Retina XDR OLED",
    dungLuongRam: "6 GB",
    dungLuongRam1: "6 GB",
    boNhoTrong: "128 GB",
    boNhoTrong1: "128 GB",
    pin: "4352mAh",
    pin1: "4352mAh",
    heDieuHanh: "iOS15",
    heDieuHanh1: "iOS15",
    doPhanGiaiManHinh: "2778 x 1284 pixel",
    tanSoQuet: "120Hz",
    kieuManHinh: "Tai thỏ",
    cameraSau: "Camera góc rộng: 12MP, ƒ/1.5\nCamera góc siêu rộng: 12MP, ƒ/1.8\nCamera tele: 12MP, ƒ/2.8",
    cameraTruoc: "12MP, ƒ/2.2",
    loaiCPU: "3.22 GHz",
    chipsetVaGPU: "Chipset",
    chip: "Apple A15 Bionic 6 nhân",
    congNgheSac: "Sạc nhanh 20W, Sạc không dây, Sạc không dây MagSafe, Tiết kiệm pin",
    theSim: "2 SIM (nano SIM và eSIM)",
    hoTroMang: "5G",
    wifi: "Wi-Fi MIMO, Wi-Fi hotspot, Wi-Fi 802.11 a/b/g/n/ac/ax, Dual-band (2.4 GHz/5 GHz)",
    kichThuoc: "160.8 x 78.1 x 7.65mm",
    trongLuong: "240g",
    chatLieuKhungVien: "Kim loại",
    chatLieuMatLung: "Kính",
}


let sp4 = {
    masp: 4,
    tensp: 'iPhone 11 64GB | Chính hãng VN/A',
    tensp1: 'iPhone 11 64GB | Chính hãng VN/A',
    tensp2: 'iPhone 11 64GB | Chính hãng VN/A',
    hinhanh: '../images/ChiTietiPhone/ip11_trang64_1.png',
    hinhanh1: '../images/ChiTietiPhone/ip11_trang64_2.png',
    hinhanh2: '../images/ChiTietiPhone/ip11_trang64_3.png',
    hinhanh3: '../images/ChiTietiPhone/ip11_trang64_1.png',
    hinhanh4: '../images/ChiTietiPhone/ip11_trang64_2.png',
    hinhanh5: '../images/ChiTietiPhone/ip11_trang64_3.png',
    hinhanh6: '../images/ChiTietiPhone/iP11_Trang64-removebg-preview.png',
    soDanhGia: "137 đánh giá",
    loaiPhienBan: "64 GB",
    giaHienTai: "9.890.000đ",
    giaHienTai1: "9.890.000đ",
    giaGiam: "11.290.000đ",
    mauSac: "Trắng",
    kichThuocManHinh: '6.1"',
    kichThuocManHinh1: '6.1"',
    congNgheManHinh: "IPS LCD",
    congNgheManHinh1: "IPS LCD",
    dungLuongRam: "4 GB",
    dungLuongRam1: "4 GB",
    boNhoTrong: "64 GB",
    boNhoTrong1: "64 GB",
    pin: "3110 mAh",
    pin1: "3110 mAh",
    heDieuHanh: "iOS 13 hoặc cao hơn (Tùy vào phiên bản phát hành)",
    heDieuHanh1: "iOS 13 hoặc cao hơn (Tùy vào phiên bản phát hành)",
    doPhanGiaiManHinh: "1792 x 828 pixel",
    tanSoQuet: "60Hz",
    kieuManHinh: "Tai thỏ",
    cameraSau: "Camera kép 12MP:\n- Camera góc rộng: ƒ/1.8 aperture\n- Camera siêu rộng: ƒ/2.4 aperture",
    cameraTruoc: "12 MP, ƒ/2.2 aperture",
    loaiCPU: "Hexa-core",
    chipsetVaGPU: "Chipset",
    chip: "A13 Bionic",
    congNgheSac: "Sạc nhanh 18W\nPower Delivery 2.0",
    theSim: "Nano-SIM + eSIM",
    hoTroMang: "4G",
    wifi: "802.11ax Wi Fi 6 with 2x2 MIMO",
    kichThuoc: "150.9mm - 75.7mm - 8.3mm",
    trongLuong: "194 g",
    chatLieuKhungVien: "Kim loại",
    chatLieuMatLung: "Kính",
}


let sp5 = {
    masp: 5,
    tensp: 'iPhone 12 64GB | Chính hãng VN/A',
    tensp1: 'iPhone 12 64GB | Chính hãng VN/A',
    tensp2: 'iPhone 12 64GB | Chính hãng VN/A',
    hinhanh: '../images/ChiTietiPhone/iphone-12-do_1.png',
    hinhanh1: '../images/ChiTietiPhone/iphone-12-do2.png',
    hinhanh2: '../images/ChiTietiPhone/iphone-12-do_3.png',
    hinhanh3: '../images/ChiTietiPhone/iphone-12-do_1.png',
    hinhanh4: '../images/ChiTietiPhone/iphone-12-do2.png',
    hinhanh5: '../images/ChiTietiPhone/iphone-12-do_3.png',
    hinhanh6: '../images/ChiTietiPhone/ip12_do64-removebg-preview.png',
    soDanhGia: "70 đánh giá",
    loaiPhienBan: "64 GB",
    giaHienTai: "12.190.000đ",
    giaHienTai1: "12.190.000đ",
    giaGiam: "15.990.000đ",
    mauSac: "Đỏ",
    kichThuocManHinh: '6.1"',
    kichThuocManHinh1: '6.1"',
    congNgheManHinh: "OLED",
    congNgheManHinh1: "OLED",
    dungLuongRam: "4 GB",
    dungLuongRam1: "4 GB",
    boNhoTrong: "64 GB",
    boNhoTrong1: "64 GB",
    pin: "Li-Ion, sạc nhanh 20W, sạc không dây 15W, USB Power Delivery 2.0",
    pin1: "Li-Ion, sạc nhanh 20W, sạc không dây 15W, USB Power Delivery 2.0",
    heDieuHanh: "iOS 14.1 hoặc cao hơn (Tùy vào phiên bản phát hành)",
    heDieuHanh1: "iOS 14.1 hoặc cao hơn (Tùy vào phiên bản phát hành)",
    doPhanGiaiManHinh: "1170 x 2532 pixels",
    tanSoQuet: "60Hz",
    kieuManHinh: "Tai thỏ",
    cameraSau: "12 MP, f/1.6, 26mm (wide), 1.4µm, dual pixel PDAF, OIS\n12 MP, f/2.4, 120˚, 13mm (ultrawide), 1/3.6\"",
    cameraTruoc: "12 MP, f/2.2, 23mm (wide), 1/3.6\"\nSL 3D, (depth/biometrics sensor)",
    loaiCPU: "Hexa-core",
    chipsetVaGPU: "Chipset",
    chip: "Apple A14 Bionic",
    congNgheSac: "Sạc nhanh 20W\nPower Delivery 2.0",
    theSim: "2 SIM (nano SIM và eSIM)",
    hoTroMang: "5G",
    wifi: "Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, hotspot",
    kichThuoc: "146.7 x 71.5 x 7.4 mm",
    trongLuong: "164 g",
    chatLieuKhungVien: "Kim loại",
    chatLieuMatLung: "Kính",
}


let sp6 = {
    masp: 6,
    tensp: 'iPhone 14 Pro Max 128GB | Chính hãng VN/A',
    tensp1: 'iPhone 14 Pro Max 128GB | Chính hãng VN/A',
    tensp2: 'iPhone 14 Pro Max 128GB | Chính hãng VN/A',
    hinhanh: '../images/ChiTietiPhone/iphone-14-pro-max_1.png',
    hinhanh1: '../images/ChiTietiPhone/iphone-14-pro-max_2.png',
    hinhanh2: '../images/ChiTietiPhone/iphone-14-pro-max_3.png',
    hinhanh3: '../images/ChiTietiPhone/iphone-14-pro-max_1.png',
    hinhanh4: '../images/ChiTietiPhone/iphone-14-pro-max_2.png',
    hinhanh5: '../images/ChiTietiPhone/iphone-14-pro-max_3.png',
    hinhanh6: '../images/ChiTietiPhone/ip14_ProMaxTim-removebg-preview.png',
    soDanhGia: "55 đánh giá",
    loaiPhienBan: "128 GB",
    giaHienTai: "26.990.000đ",
    giaHienTai1: "26.990.000đ",
    giaGiam: "29.990.000đ",
    mauSac: "Tím",
    kichThuocManHinh: '6.7"',
    kichThuocManHinh1: '6.7"',
    congNgheManHinh: "Super Retina XDR OLED",
    congNgheManHinh1: "Super Retina XDR OLED",
    dungLuongRam: "6 GB",
    dungLuongRam1: "6 GB",
    boNhoTrong: "128 GB",
    boNhoTrong1: "128 GB",
    pin: "4.323 mAh",
    pin1: "4.323 mAh",
    heDieuHanh: "iOS 16",
    heDieuHanh1: "iOS 16",
    doPhanGiaiManHinh: "2796 x 1290-pixel",
    tanSoQuet: "120Hz",
    kieuManHinh: "Dynamic Island",
    cameraSau: "Camera chính: 48 MP, f/1.8, 24mm, 1.22µm, PDAF, OIS\nCamera góc siêu rộng: 12 MP, f/2.2, 13mm, 120˚, 1.4µm, PDAF\nCamera tele: 12 MP, f/2.8, 77mm (telephoto), PDAF, OIS, 3x optical zoom\nCảm biến độ sâu TOF 3D LiDAR",
    cameraTruoc: "Camera selfie: 12 MP, f/1.9, 23mm, 1/3.6\", PDAF",
    loaiCPU: "Hexa-core",
    chipsetVaGPU: "Chipset",
    chip: "Apple A16 Bionic",
    congNgheSac: "Sạc nhanh PD 2.0 30W (30 phút sạc được 50%)\nSạc không dây MagSafe 15W\nSạc không dây chuẩn Qi 7.5W",
    theSim: "2 SIM (nano SIM và eSIM)",
    hoTroMang: "5G",
    wifi: "Wi-Fi MIMO, Dual-band (2.4 GHz/5 GHz), Wi-Fi 802.11 a/b/g/n/ac/ax, Wi-Fi hotspot",
    kichThuoc: "160.7 x 77.6 x 7.9 mm",
    trongLuong: "240 gr",
    chatLieuKhungVien: "Kim loại",
    chatLieuMatLung: "Kính",
}

let sp7 = {
    masp: 7,
    tensp: 'iPhone 12 128GB | Chính hãng VN/A',
    tensp1: 'iPhone 12 128GB | Chính hãng VN/A',
    tensp2: 'iPhone 12 128GB | Chính hãng VN/A',
    hinhanh: '../images/ChiTietiPhone/iphone-12-xanh-la-1.png',
    hinhanh1: '../images/ChiTietiPhone/iphone-12-xanh-la-2.png',
    hinhanh2: '../images/ChiTietiPhone/iphone-12-xanh-la-3.png',
    hinhanh3: '../images/ChiTietiPhone/iphone-12-xanh-la-1.png',
    hinhanh4: '../images/ChiTietiPhone/iphone-12-xanh-la-2.png',
    hinhanh5: '../images/ChiTietiPhone/iphone-12-xanh-la-3.png',
    hinhanh6: '../images/ChiTietiPhone/ip12_xanhLa128-removebg-preview.png',
    soDanhGia: "23 đánh giá",
    loaiPhienBan: "128 GB",
    giaHienTai: "13.290.000đ",
    giaHienTai1: "13.290.000đ",
    giaGiam: "17.990.000đ",
    mauSac: "Xanh lá",
    kichThuocManHinh: '6.1"',
    kichThuocManHinh1: '6.1"',
    congNgheManHinh: "OLED",
    congNgheManHinh1: "OLED",
    dungLuongRam: "4 GB",
    dungLuongRam1: "4 GB",
    boNhoTrong: "128 GB",
    boNhoTrong1: "128 GB",
    pin: "Li-Ion, sạc nhanh 20W, sạc không dây 15W, USB Power Delivery 2.0",
    pin1: "Li-Ion, sạc nhanh 20W, sạc không dây 15W, USB Power Delivery 2.0",
    heDieuHanh: "iOS 14.1 hoặc cao hơn (Tùy vào phiên bản phát hành)",
    heDieuHanh1: "iOS 14.1 hoặc cao hơn (Tùy vào phiên bản phát hành)",
    doPhanGiaiManHinh: "1170 x 2532 pixels",
    tanSoQuet: "60Hz",
    kieuManHinh: "Tai thỏ",
    cameraSau: "12 MP, f/1.6, 26mm (wide), 1.4µm, dual pixel PDAF, OIS\n12 MP, f/2.4, 120˚, 13mm (ultrawide), 1/3.6\"",
    cameraTruoc: "12 MP, f/2.2, 23mm (wide), 1/3.6\"",
    loaiCPU: "Hexa-core",
    chipsetVaGPU: "Chipset",
    chip: "Apple A14 Bionic",
    congNgheSac: "Sạc nhanh 20W\nPower Delivery 2.0",
    theSim: "2 SIM (nano SIM và eSIM)",
    hoTroMang: "5G",
    wifi: "Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, hotspot",
    kichThuoc: "146.7 x 71.5 x 7.4 mm",
    trongLuong: "164 g",
    chatLieuKhungVien: "Kim loại",
    chatLieuMatLung: "Kính",
}

let sp8 = {
    masp: 8,
    tensp: 'iPhone 13 128GB | Chính hãng VN/A',
    tensp1: 'iPhone 13 128GB | Chính hãng VN/A',
    tensp2: 'iPhone 13 128GB | Chính hãng VN/A',
    hinhanh: '../images/ChiTietiPhone/iphone-13Hong_1.png',
    hinhanh1: '../images/ChiTietiPhone/iphone-13Hong_2.png',
    hinhanh2: '../images/ChiTietiPhone/iphone-13Hong_3.png',
    hinhanh3: '../images/ChiTietiPhone/iphone-13Hong_1.png',
    hinhanh4: '../images/ChiTietiPhone/iphone-13Hong_2.png',
    hinhanh5: '../images/ChiTietiPhone/iphone-13Hong_3.png',
    hinhanh6: '../images/ChiTietiPhone/ip13_hong128-removebg-preview.png',
    soDanhGia: "162 đánh giá",
    loaiPhienBan: "128 GB",
    giaHienTai: "13.990.000đ",
    giaHienTai1: "13.990.000đ",
    giaGiam: "18.990.000đ",
    mauSac: "Hồng",
    kichThuocManHinh: '6.1"',
    kichThuocManHinh1: '6.1"',
    congNgheManHinh: "Super Retina XDR OLED",
    congNgheManHinh1: "Super Retina XDR OLED",
    dungLuongRam: "4 GB",
    dungLuongRam1: "4 GB",
    boNhoTrong: "128 GB",
    boNhoTrong1: "128 GB",
    pin: "3240mAh",
    pin1: "3240mAh",
    heDieuHanh: "iOS 15",
    heDieuHanh1: "iOS 15",
    doPhanGiaiManHinh: "2532 x 1170 pixels",
    tanSoQuet: "60Hz",
    kieuManHinh: "Tai thỏ",
    cameraSau: "Camera góc rộng: 12MP, f/1.6\nCamera góc siêu rộng: 12MP, ƒ/2.4",
    cameraTruoc: "12MP, f/2.2",
    loaiCPU: "3.22 GHz",
    chipsetVaGPU: "Chipset",
    chip: "Apple A15",
    congNgheSac: "Sạc nhanh 20W, Sạc không dây, Sạc ngược không dây 15W, Sạc pin nhanh, Tiết kiệm pin",
    theSim: "2 SIM (nano SIM và eSIM)",
    hoTroMang: "5G",
    wifi: "Wi Fi 6 (802.11ax)",
    kichThuoc: "146,7 x 71,5 x 7,65mm",
    trongLuong: "173g",
    chatLieuKhungVien: "Nhôm",
    chatLieuMatLung: "Kính",
}

let sp9 = {
    masp: 9,
    tensp: 'iPhone 13 Pro Max 128GB | Chính hãng VN/A',
    tensp1: 'iPhone 13 Pro Max 128GB | Chính hãng VN/A',
    tensp2: 'iPhone 13 Pro Max 128GB | Chính hãng VN/A',
    hinhanh: '../images/ChiTietiPhone/iphone-13-pro-max-xanh-1.png',
    hinhanh1: '../images/ChiTietiPhone/iphone-13-pro-max-xanh-2.png',
    hinhanh2: '../images/ChiTietiPhone/iphone-13-pro-max-xanh-3.png',
    hinhanh3: '../images/ChiTietiPhone/iphone-13-pro-max-xanh-1.png',
    hinhanh4: '../images/ChiTietiPhone/iphone-13-pro-max-xanh-2.png',
    hinhanh5: '../images/ChiTietiPhone/iphone-13-pro-max-xanh-3.png',
    hinhanh6: '../images/ChiTietiPhone/iP13_promax_xanhduong-removebg-preview.png',
    soDanhGia: "52 đánh giá",
    loaiPhienBan: "128 GB",
    giaHienTai: "15.890.000đ",
    giaHienTai1: "15.890.000đ",
    giaGiam: "17.290.000đ",
    mauSac: "Xám",
    kichThuocManHinh: '6.7"',
    kichThuocManHinh1: '6.7"',
    congNgheManHinh: "Super Retina XDR OLED",
    congNgheManHinh1: "Super Retina XDR OLED",
    dungLuongRam: "6 GB",
    dungLuongRam1: "6 GB",
    boNhoTrong: "128 GB",
    boNhoTrong1: "128 GB",
    pin: "4352mAh",
    pin1: "4352mAh",
    heDieuHanh: "iOS15",
    heDieuHanh1: "iOS15",
    doPhanGiaiManHinh: "2778 x 1284 pixel",
    tanSoQuet: "120Hz",
    kieuManHinh: "Tai thỏ",
    cameraSau: "Camera góc rộng: 12MP, ƒ/1.5\nCamera góc siêu rộng: 12MP, ƒ/1.8\nCamera tele: 12MP, ƒ/2.8",
    cameraTruoc: "12MP, ƒ/2.2",
    loaiCPU: "3.22 GHz",
    chipsetVaGPU: "Chipset",
    chip: "Apple A15 Bionic 6 nhân",
    congNgheSac: "Sạc nhanh 20W, Sạc không dây, Sạc không dây MagSafe, Tiết kiệm pin",
    theSim: "2 SIM (nano SIM và eSIM)",
    hoTroMang: "5G",
    wifi: "Wi-Fi MIMO, Wi-Fi hotspot, Wi-Fi 802.11 a/b/g/n/ac/ax, Dual-band (2.4 GHz/5 GHz)",
    kichThuoc: "160.8 x 78.1 x 7.65mm",
    trongLuong: "240g",
    chatLieuKhungVien: "Kim loại",
    chatLieuMatLung: "Kính",
}

let sp10 = {
    masp: 10,
    tensp: 'iPhone 14 128GB | Chính hãng VN/A',
    tensp1: 'iPhone 14 128GB | Chính hãng VN/A',
    tensp2: 'iPhone 14 128GB | Chính hãng VN/A',
    hinhanh: '../images/ChiTietiPhone/ip14_vang_1.png',
    hinhanh1: '../images/ChiTietiPhone/ip14_vang_2.png',
    hinhanh2: '../images/ChiTietiPhone/ip14_vang_3.png',
    hinhanh3: '../images/ChiTietiPhone/ip14_vang_1.png',
    hinhanh4: '../images/ChiTietiPhone/ip14_vang_2.png',
    hinhanh5: '../images/ChiTietiPhone/ip14_vang_3.png',
    hinhanh6: '../images/ChiTietiPhone/ip14_128GBVang-removebg-preview.png',
    soDanhGia: "3 đánh giá",
    loaiPhienBan: "128 GB",
    giaHienTai: "17.390.000đ",
    giaHienTai1: "17.390.000đ",
    giaGiam: "22.990.000đ",
    mauSac: "Vàng",
    kichThuocManHinh: '6.1"',
    kichThuocManHinh1: '6.1"',
    congNgheManHinh: "OLED",
    congNgheManHinh1: "OLED",
    dungLuongRam: "6 GB",
    dungLuongRam1: "6 GB",
    boNhoTrong: "128 GB",
    boNhoTrong1: "128 GB",
    pin: "3,279mAh",
    pin1: "3,279mAh",
    heDieuHanh: "iOS 16",
    heDieuHanh1: "iOS 16",
    doPhanGiaiManHinh: "2532 x 1170 pixels",
    tanSoQuet: "60Hz",
    kieuManHinh: "Tai thỏ",
    cameraSau: "Camera góc rộng: 12MP, ƒ/1.5\nCamera góc siêu rộng: 12MP, ƒ/2.4",
    cameraTruoc: "12MP, ƒ/1.9",
    loaiCPU: "3.22 GHz",
    chipsetVaGPU: "Chipset",
    chip: "Apple A15 Bionic 6 nhân",
    congNgheSac: "Sạc nhanh 20W\nTiết kiệm pin\nSạc không dây\nSạc không dây MagSafe",
    theSim: "2 SIM (nano SIM và eSIM)",
    hoTroMang: "5G",
    wifi: "Wi-Fi MIMO, Dual-band (2.4 GHz/5 GHz), Wi-Fi 802.11 a/b/g/n/ac/ax, Wi-Fi hotspot",
    kichThuoc: "146.7 x 71.5 x 7.8 mm",
    trongLuong: "172 g",
    chatLieuKhungVien: "Nhôm",
    chatLieuMatLung: "Kính",
}

let sp11 = {
    masp: 11,
    tensp: 'Samsung Galaxy S23 Ultra 8GB 256GB | Chính hãng VN/A',
    tensp1: 'Samsung Galaxy S23 Ultra 8GB 256GB | Chính hãng VN/A',
    tensp2: 'Samsung Galaxy S23 Ultra 8GB 256GB | Chính hãng VN/A',
    hinhanh: '../images/SamSung/samsungXanhReu_1.jpg',
    hinhanh1: '../images/SamSung/samsungXanhReu_2.jpg',
    hinhanh2: '../images/SamSung/samsungXanhReu_3.jpg',
    hinhanh3: '../images/SamSung/samsungXanhReu_1.jpg',
    hinhanh4: '../images/SamSung/samsungXanhReu_2.jpg',
    hinhanh5: '../images/SamSung/samsungXanhReu_3.jpg',
    hinhanh6: '../images/SamSung/samsungXanh_left.png',
    soDanhGia: "19 đánh giá",
    loaiPhienBan: "256 GB",
    giaHienTai: "24.990.000₫",
    giaHienTai1: "24.990.000₫",
    giaGiam: "31.990.000₫",
    mauSac: "Xanh Rêu",
    kichThuocManHinh: '6.8"',
    kichThuocManHinh1: '6.8"',
    congNgheManHinh: "Dynamic AMOLED 2X",
    congNgheManHinh1: "Dynamic AMOLED 2X",
    dungLuongRam: "8GB",
    dungLuongRam1: "8GB",
    boNhoTrong: "256GB",
    boNhoTrong1: "256GB",
    pin: "5000 mAh",
    pin1: "5000 mAh",
    heDieuHanh: "Android 13",
    heDieuHanh1: "Android 13",
    doPhanGiaiManHinh: "1440 x 3088 pixels (QHD+)",
    tanSoQuet: "120Hz",
    kieuManHinh: "Giọt nước",
    cameraSau: "Siêu rộng: 12MP, F2.2 (Dual Pixel AF); Chính: 200MP, F1.7 OIS ±3° (Super Quad Pixel AF); Tele 1: 10MP, F4.9 (10X, Dual Pixel AF) OIS, Tele 2: 10MP, F2.4 (3X, Dual Pixel AF) OIS Thu phóng chuẩn không gian 100X",
    cameraTruoc: "12MP, F2.2 (Dual Pixel AF)",
    loaiCPU: "1x3.36 GHz Cortex-X3 & 2x2.8 GHz Cortex-A715 & 2x2.8 GHz Cortex-A710 & 3x2.0 GHz Cortex-A510",
    chipsetVaGPU: "Chipset",
    chip: "Snapdragon 8 Gen 2 (4 nm)",
    congNgheSac: "Sạc có dây: 45W có dây; Sạc không dây: 15W (Qi/PMA); Chia sẻ pin không dây",
    theSim: "2 Nano SIM hoặc 1 Nano + 1 eSIM",
    hoTroMang: "5G",
    wifi: "Wi-Fi 802.11 a/b/g/n/ac/6e, tri-band, Wi-Fi Direct",
    kichThuoc: "163.4 x 78.1 x 8.9 mm",
    trongLuong: "233 g",
    chatLieuKhungVien: "Nhôm",
    chatLieuMatLung: "Kính",
}

let sp12 = {
    masp: 12,
    tensp: 'Samsung Galaxy S24 Ultra 12GB 256GB | Chính hãng VN/A',
    tensp1: 'Samsung Galaxy S24 Ultra 12GB 256GB | Chính hãng VN/A',
    tensp2: 'Samsung Galaxy S24 Ultra 12GB 256GB | Chính hãng VN/A',
    hinhanh: '../images/SamSung/samsung-galaxy-s24-ultra-xam-1.png',
    hinhanh1: '../images/SamSung/samsung-galaxy-s24-ultra-xam-2.png',
    hinhanh2: '../images/SamSung/samsung-galaxy-s24-ultra-xam-3.png',
    hinhanh3: '../images/SamSung/samsung-galaxy-s24-ultra-xam-1.png',
    hinhanh4: '../images/SamSung/samsung-galaxy-s24-ultra-xam-2.png',
    hinhanh5: '../images/SamSung/samsung-galaxy-s24-ultra-xam-3.png',
    hinhanh6: '../images/SamSung/SSGS24_Ultra-removebg-preview.png',
    soDanhGia: "175 đánh giá",
    loaiPhienBan: "256GB",
    giaHienTai: "26.390.000₫",
    giaHienTai1: "26.390.000₫",
    giaGiam: "33.990.000đ",
    mauSac: 'Xám',
    kichThuocManHinh: '6.8"',
    kichThuocManHinh1: '6.8"',
    congNgheManHinh: "Dynamic AMOLED 2X",
    congNgheManHinh1: "Dynamic AMOLED 2X",
    dungLuongRam: "12 GB",
    dungLuongRam1: "12 GB",
    boNhoTrong: "256 GB",
    boNhoTrong1: "256 GB",
    pin: "5,000mAh",
    pin1: "5,000mAh",
    heDieuHanh: "Android 14, One UI 6.1",
    heDieuHanh1: "Android 14, One UI 6.1",
    doPhanGiaiManHinh: "1440 x 3120 pixels",
    tanSoQuet: "120Hz",
    kieuManHinh: "Đục lỗ (Nốt ruồi)",
    cameraSau: "Camera chính: 200MP, Laser AF, OIS; Camera: 50MP, PDAF, OIS, zoom quang học 5x; Camera tele: 10MP; Camera góc siêu rộng: 12 MP, f/2.2, 13mm, 120˚",
    cameraTruoc: "12 MP, f/2.2",
    loaiCPU: "Snapdragon 8 Gen 3 For Galaxy",
    chipsetVaGPU: "Chipset",
    chip: "Adreno 750 (1 GHz)",
    congNgheSac: "Sạc nhanh 45W, Chia sẻ pin không dây, Sạc siêu nhanh, Sạc không dây",
    theSim: "SIM 1 + SIM 2 / SIM 1 + eSIM / 2 eSIM",
    hoTroMang: "5G",
    wifi: "802.11a/b/g/n/ac/ax/be 2.4GHz+5GHz+6GHz, EHT320, MIMO, 4096-QAM",
    kichThuoc: "162.3 x 79.0 x 8.6mm",
    trongLuong: "232g",
    chatLieuKhungVien: "Titanium",
    chatLieuMatLung: "Kính",
}

let sp13 = {
    masp: 13,
    tensp: 'Samsung Galaxy S22 Ultra (12GB - 256GB) | Chính hãng VN/A',
    tensp1: 'Samsung Galaxy S22 Ultra (12GB - 256GB) | Chính hãng VN/A',
    tensp2: 'Samsung Galaxy S22 Ultra (12GB - 256GB) | Chính hãng VN/A',
    hinhanh: '../images/SamSung/samsung-galaxy-s22-ultra-den-1.png',
    hinhanh1: '../images/SamSung/samsung-galaxy-s22-ultra-den-2.png',
    hinhanh2: '../images/SamSung/samsung-galaxy-s22-ultra-den-3.png',
    hinhanh3: '../images/SamSung/samsung-galaxy-s22-ultra-den-1.png',
    hinhanh4: '../images/SamSung/samsung-galaxy-s22-ultra-den-2.png',
    hinhanh5: '../images/SamSung/samsung-galaxy-s22-ultra-den-3.png',
    hinhanh6: '../images/SamSung/samsung-galaxy-s22-ultra-den-removebg-preview.png',
    soDanhGia: "150 đánh giá",
    loaiPhienBan: "256GB",
    giaHienTai: "17.990.000₫",
    giaHienTai1: "17.990.000₫",
    giaGiam: "33.990.000đ",
    mauSac: 'Đen',
    kichThuocManHinh: '6.8"',
    kichThuocManHinh1: '6.8"',
    congNgheManHinh: "Dynamic AMOLED 2X",
    congNgheManHinh1: "Dynamic AMOLED 2X",
    dungLuongRam: "12 GB",
    dungLuongRam1: "12 GB",
    boNhoTrong: "256 GB",
    boNhoTrong1: "256 GB",
    pin: "5000 mAh",
    pin1: "5000 mAh",
    heDieuHanh: "Android 12",
    heDieuHanh1: "Android 12",
    doPhanGiaiManHinh: "1440 x 3088 pixels (QHD+)",
    tanSoQuet: "120Hz",
    kieuManHinh: "Đục lỗ (Nốt ruồi)",
    cameraSau: "108 MP, f/1.8 góc rộng; 10 MP, f/4.9; 10 MP, f/2.4; 12 MP, f/2.2 góc siêu rộng",
    cameraTruoc: "40 MP, f/2.2",
    loaiCPU: "Snapdragon 8 Gen 1 (4 nm)",
    chipsetVaGPU: "Chipset",
    chip: "Adreno 730",
    congNgheSac: "Sạc pin nhanh 45W, Sạc không dây Qi, Sạc không dây ngược 4,5W",
    theSim: "2 Nano SIM hoặc 1 Nano + 1 eSIM",
    hoTroMang: "5G",
    wifi: "Wi-Fi 802.11 a/b/g/n/ac/6e, dual-band, Wi-Fi Direct, hotspot",
    bluetooth: "5.2, A2DP, LE",
    gps: "GPS GLONASS GALILEO QZSS BEIDOU",
    kichThuoc: "163.3 x 77.9 x 8.9 mm",
    trongLuong: "228 g",
    chatLieuMatLung: "Kính",
    chatLieuKhungVien: "Kim loại",
}

let sp14 = {
    masp: 14,
    tensp: 'Samsung Galaxy A55 5G 8GB 128GB | Chính hãng VN/A',
    tensp1: 'Samsung Galaxy A55 5G 8GB 128GB | Chính hãng VN/A',
    tensp2: 'Samsung Galaxy A55 5G 8GB 128GB | Chính hãng VN/A',
    hinhanh: '../images/SamSung/samsung-galaxy-A55-tim_1.png',
    hinhanh1: '../images/SamSung/samsung-galaxy-A55-tim_2.png',
    hinhanh2: '../images/SamSung/samsung-galaxy-A55-tim_3.png',
    hinhanh3: '../images/SamSung/samsung-galaxy-A55-tim_1.png',
    hinhanh4: '../images/SamSung/samsung-galaxy-A55-tim_2.png',
    hinhanh5: '../images/SamSung/samsung-galaxy-A55-tim_3.png',
    hinhanh6: '../images/SamSung/samsung-galaxy-A55-tim-removebg-preview.png',
    soDanhGia: "120 đánh giá",
    loaiPhienBan: "128GB",
    giaHienTai: "9.690.000₫",
    giaHienTai1: "9.690.000₫",
    giaGiam: "9.990.000đ",
    mauSac: 'Tím',
    kichThuocManHinh: '6.6"',
    kichThuocManHinh1: '6.6"',
    congNgheManHinh: "Super AMOLED",
    congNgheManHinh1: "Super AMOLED",
    dungLuongRam: "8 GB",
    dungLuongRam1: "8 GB",
    boNhoTrong: "128 GB",
    boNhoTrong1: "128 GB",
    pin: "5000 mAh",
    pin1: "5000 mAh",
    heDieuHanh: "Android 14",
    heDieuHanh1: "Android 14",
    doPhanGiaiManHinh: "1080 x 2400 pixels (FullHD+)",
    tanSoQuet: "120Hz",
    kieuManHinh: "Đục lỗ (Nốt ruồi)",
    cameraSau: "Camera chính: 50 MP OIS+HDR; Camera góc rộng: 12MP; Camera macro: 5MP",
    cameraTruoc: "32 MP",
    loaiCPU: "Exynos 1480 4nm 2.4GHz",
    chipsetVaGPU: "Chipset",
    chip: "AMD Titan 1WGP",
    congNgheSac: "Sạc nhanh 25W",
    theSim: "2 SIM (Nano-SIM)",
    hoTroMang: "5G",
    wifi: "802.11 a/b/g/n/ac/ax 2.4GHz+5GHz, WiFi Direct",
    bluetooth: "v5.3",
    gps: "GPS, Glonass, Beidou, Galileo, QZSS",
    kichThuoc: "161.1 x 77.4 x 8.2 mm",
    trongLuong: "213g",
    chatLieuMatLung: "Nhựa",
    chatLieuKhungVien: "Kim loại",
}

let sp15 = {
    masp: 15,
    tensp: 'Samsung Galaxy A15 LTE 8GB 128GB | Chính hãng VN/A',
    tensp1: 'Samsung Galaxy A15 LTE 8GB 128GB | Chính hãng VN/A',
    tensp2: 'Samsung Galaxy A15 LTE 8GB 128GB | Chính hãng VN/A',
    hinhanh: '../images/SamSung/samsung-galaxy-a15-xanh-1.png',
    hinhanh1: '../images/SamSung/samsung-galaxy-a15-xanh-2.png',
    hinhanh2: '../images/SamSung/samsung-galaxy-a15-xanh-3.png',
    hinhanh3: '../images/SamSung/samsung-galaxy-a15-xanh-1.png',
    hinhanh4: '../images/SamSung/samsung-galaxy-a15-xanh-2.png',
    hinhanh5: '../images/SamSung/samsung-galaxy-a15-xanh-3.png',
    hinhanh6: '../images/SamSung/samsung-galaxy-A15-xanh-removebg-preview.png',
    soDanhGia: "185 đánh giá",
    loaiPhienBan: "128GB",
    giaHienTai: "4.790.000₫",
    giaHienTai1: "4.790.000₫",
    giaGiam: "4.990.000đ",
    mauSac: 'Xanh',
    kichThuocManHinh: '6.5"',
    kichThuocManHinh1: '6.5"',
    congNgheManHinh: "Super AMOLED",
    congNgheManHinh1: "Super AMOLED",
    dungLuongRam: "8 GB",
    dungLuongRam1: "8 GB",
    boNhoTrong: "128 GB",
    boNhoTrong1: "128 GB",
    pin: "5000 mAh",
    pin1: "5000 mAh",
    heDieuHanh: "Android 14",
    heDieuHanh1: "Android 14",
    doPhanGiaiManHinh: "1080 x 2340 pixels (FullHD+)",
    tanSoQuet: "90Hz",
    kieuManHinh: "Giọt nước",
    cameraSau: "Camera chính: 50 MP & Phụ 5 MP, 2 MP",
    cameraTruoc: "13MP",
    loaiCPU: "MediaTek Helio G99 8 nhân",
    chipsetVaGPU: "Chipset",
    chip: "Mali-G57",
    congNgheSac: "Sạc nhanh 25W",
    theSim: "2 SIM (Nano-SIM)",
    hoTroMang: "4G",
    wifi: "Dual-band (2.4 GHz/5 GHz) Wi-Fi 802.11 a/b/g/n/ac Wi-Fi Direct",
    bluetooth: "v5.3",
    gps: "BEIDOU GALILEO GLONASS GPS QZSS",
    kichThuoc: "160.1 x 76.8 x 8.4 mm",
    trongLuong: "200 g",
    chatLieuMatLung: "Nhựa",
    chatLieuKhungVien: "Nhựa",
}

let sp16 = {
    masp: 16,
    tensp: 'Samsung Galaxy S24 8GB 256GB',
    tensp1: 'Samsung Galaxy S24 8GB 256GB',
    tensp2: 'Samsung Galaxy S24 8GB 256GB',
    hinhanh: '../images/SamSung/samsung-galaxy-s24-tim-1.png',
    hinhanh1: '../images/SamSung/samsung-galaxy-s24-tim-2.png',
    hinhanh2: '../images/SamSung/samsung-galaxy-s24-tim-3.png',
    hinhanh3: '../images/SamSung/samsung-galaxy-s24-tim-1.png',
    hinhanh4: '../images/SamSung/samsung-galaxy-s24-tim-2.png',
    hinhanh5: '../images/SamSung/samsung-galaxy-s24-tim-3.png',
    hinhanh6: '../images/SamSung/samsung-galaxy-s24-tim-removebg-preview.png',
    soDanhGia: "145 đánh giá",
    loaiPhienBan: "256GB",
    giaHienTai: "16.990.000₫",
    giaHienTai1: "16.990.000₫",
    giaGiam: "22.990.000đ",
    mauSac: 'Tím',
    kichThuocManHinh: '6.2"',
    kichThuocManHinh1: '6.2"',
    congNgheManHinh: "Dynamic AMOLED 2X",
    congNgheManHinh1: "Dynamic AMOLED 2X",
    dungLuongRam: "8 GB",
    dungLuongRam1: "8 GB",
    boNhoTrong: "256 GB",
    boNhoTrong1: "256 GB",
    pin: "4000 mAh",
    pin1: "4000 mAh",
    heDieuHanh: "Android 14, One UI 6.1",
    heDieuHanh1: "Android 14, One UI 6.1",
    doPhanGiaiManHinh: "1080 x 2340 pixels (FullHD+)",
    tanSoQuet: "120Hz",
    kieuManHinh: "Đục lỗ (Nốt ruồi)",
    cameraSau: "Camera chính 50 MP, f/1.8",
    cameraTruoc: "12 MP, f/2.2",
    loaiCPU: "Exynos 2400",
    chipsetVaGPU: "Chipset",
    chip: "Xclipse 940",
    congNgheSac: "Sạc nhanh 25W, Chia sẻ pin không dây, Sạc siêu nhanh, Sạc không dây",
    theSim: "SIM 1 + SIM 2 / SIM 1 + eSIM / 2 eSIM",
    hoTroMang: "5G",
    wifi: "802.11a/b/g/n/ac/ax 2.4GHz+5GHz+6GHz, HE160, MIMO, 1024-QAM",
    bluetooth: "Bluetooth 5.3",
    gps: "GPS, Glonass, Beidou, Galileo, QZSS",
    kichThuoc: "147.0 x 70.6 x 7.6mm",
    trongLuong: "167g",
    chatLieuMatLung: "Kính",
    chatLieuKhungVien: "Nhôm",
}

let sp17 = {
    masp: 17,
    tensp: 'Samsung Galaxy Z Fold5 12GB 512GB',
    tensp1: 'Samsung Galaxy Z Fold5 12GB 512GB',
    tensp2: 'Samsung Galaxy Z Fold5 12GB 512GB',
    hinhanh: '../images/SamSung/samsung-galaxy-z-fold5_den_1.png',
    hinhanh1: '../images/SamSung/samsung-galaxy-z-fold5_den_2.png',
    hinhanh2: '../images/SamSung/samsung-galaxy-z-fold5_den_3.png',
    hinhanh3: '../images/SamSung/samsung-galaxy-z-fold5_den_1.png',
    hinhanh4: '../images/SamSung/samsung-galaxy-z-fold5_den_2.png',
    hinhanh5: '../images/SamSung/samsung-galaxy-z-fold5_den_3.png',
    hinhanh6: '../images/SamSung/samsung-galaxy-z-fold5_den-removebg-preview.png',
    soDanhGia: "135 đánh giá",
    loaiPhienBan: "512GB",
    giaHienTai: "30.990.000₫",
    giaHienTai1: "30.990.000₫",
    giaGiam: "44.990.000₫",
    mauSac: 'Đen',
    kichThuocManHinh: '7.6"',
    kichThuocManHinh1: '7.6"',
    congNgheManHinh: "Dynamic AMOLED 2X",
    congNgheManHinh1: "Dynamic AMOLED 2X",
    dungLuongRam: "12 GB",
    dungLuongRam1: "12 GB",
    boNhoTrong: "512 GB",
    boNhoTrong1: "512 GB",
    pin: "4400 mAh",
    pin1: "4400 mAh",
    heDieuHanh: "Android 13",
    heDieuHanh1: "Android 13",
    doPhanGiaiManHinh: "2176 x 1812 pixels (QXGA+)",
    tanSoQuet: "120Hz",
    kieuManHinh: "Màn hình gập",
    cameraSau: "Camera góc rộng: 50MP, F1.8, Dual Pixel AF, OIS, 2.0μm",
    cameraTruoc: "Camera bên trong: 4 MP, F1.8",
    loaiCPU: "Snapdragon 8 Gen 2 for Galaxy (4nm) 8 nhân",
    chipsetVaGPU: "Chipset",
    chip: "Adreno 740",
    congNgheSac: "Sạc nhanh 25W, Sạc không dây, Sạc ngược không dây",
    theSim: "2 SIM (nano‑SIM và eSIM)",
    hoTroMang: "5G",
    wifi: "Dual-band (2.4 GHz/5 GHz), Wi-Fi 802.11 a/b/g/n/ac/ax, Wi-Fi MIMO",
    bluetooth: "Bluetooth v5.3",
    gps: "GLONASS, GPS, GALILEO, QZSS, BEIDOU",
    kichThuoc: "Mở: 154.9 x 129.9 x 6.1mm, Gập: 154.9 x 67.1 x 13.4mm",
    trongLuong: "253 g",
    chatLieuMatLung: "Kính",
    chatLieuKhungVien: "Nhôm",
}

let sp18 = {
    masp: 18,
    tensp: 'Samsung Galaxy A35 5G 8GB 128GB',
    tensp1: 'Samsung Galaxy A35 5G 8GB 128GB',
    tensp2: 'Samsung Galaxy A35 5G 8GB 128GB',
    hinhanh: '../images/SamSung/samsung-galaxy-a35-vang_1.png',
    hinhanh1: '../images/SamSung/samsung-galaxy-a35-vang_2.png',
    hinhanh2: '../images/SamSung/samsung-galaxy-a35-vang_3.png',
    hinhanh3: '../images/SamSung/samsung-galaxy-a35-vang_1.png',
    hinhanh4: '../images/SamSung/samsung-galaxy-a35-vang_2.png',
    hinhanh5: '../images/SamSung/samsung-galaxy-a35-vang_3.png',
    hinhanh6: '../images/SamSung/samsung-galaxy-a35-vang-removebg-preview.png',
    soDanhGia: "150 đánh giá",
    loaiPhienBan: "128GB",
    giaHienTai: "7.990.000₫",
    giaHienTai1: "7.990.000₫",
    giaGiam: "8.290.000₫",
    mauSac: 'Vàng',
    kichThuocManHinh: '6.6"',
    kichThuocManHinh1: '6.6"',
    congNgheManHinh: "Super AMOLED",
    congNgheManHinh1: "Super AMOLED",
    dungLuongRam: "8 GB",
    dungLuongRam1: "8 GB",
    boNhoTrong: "128 GB",
    boNhoTrong1: "128 GB",
    pin: "5000 mAh",
    pin1: "5000 mAh",
    heDieuHanh: "Android 14",
    heDieuHanh1: "Android 14",
    doPhanGiaiManHinh: "1080 x 2340 pixels (FullHD+)",
    tanSoQuet: "120Hz",
    kieuManHinh: "Giọt nước",
    cameraSau: "Camera chính rộng: 50 MP OIS+HDR Camera Macro: 5MP, f/2.4 Camera siêu rộng: 8MP, f/2.2",
    cameraTruoc: "13MP, f/2.2",
    loaiCPU: "Exynos 1380",
    chipsetVaGPU: "Chipset",
    chip: "Mali-G68 MP5",
    congNgheSac: "Sạc nhanh 25W",
    theSim: "2 SIM (Nano-SIM)",
    hoTroMang: "5G",
    wifi: "802.11 a/b/g/n/ac/ax 2.4GHz+5GHz WiFi Direct",
    bluetooth: "Bluetooth v5.3",
    gps: "GPS, Glonass, Beidou, Galileo, QZSS",
    kichThuoc: "161.7 x 78.0 x 8.2 mm",
    trongLuong: "209g",
    chatLieuMatLung: "Nhựa",
    chatLieuKhungVien: "Nhựa",
}

let sp19 = {
    masp: 19,
    tensp: 'Samsung Galaxy M14 5G 4GB 128GB',
    tensp1: 'Samsung Galaxy M14 5G 4GB 128GB',
    tensp2: 'Samsung Galaxy M14 5G 4GB 128GB',
    hinhanh: '../images/SamSung/samsung-galaxy-m14_xanhduong_1.png',
    hinhanh1: '../images/SamSung/samsung-galaxy-m14_xanhduong_2.png',
    hinhanh2: '../images/SamSung/samsung-galaxy-m14_xanhduong_3.png',
    hinhanh3: '../images/SamSung/samsung-galaxy-m14_xanhduong_1.png',
    hinhanh4: '../images/SamSung/samsung-galaxy-m14_xanhduong_2.png',
    hinhanh5: '../images/SamSung/samsung-galaxy-m14_xanhduong_3.png',
    hinhanh6: '../images/SamSung/samsung-galaxy-m14_xanhduong-removebg-preview.png',
    soDanhGia: "Không có đánh giá",
    loaiPhienBan: "128GB",
    giaHienTai: "3.750.000₫",
    giaHienTai1: "3.750.000₫",
    giaGiam: "5.290.000₫",
    mauSac: 'Xanh dương nhạt',
    kichThuocManHinh: '6.6"',
    kichThuocManHinh1: '6.6"',
    congNgheManHinh: "PLS LCD",
    congNgheManHinh1: "PLS LCD",
    dungLuongRam: "4 GB",
    dungLuongRam1: "4 GB",
    boNhoTrong: "128 GB",
    boNhoTrong1: "128 GB",
    pin: "6.000 mAh",
    pin1: "6.000 mAh",
    heDieuHanh: "Android 13",
    heDieuHanh1: "Android 13",
    doPhanGiaiManHinh: "1080 x 2408 pixels",
    tanSoQuet: "90Hz",
    kieuManHinh: "Giọt nước",
    cameraSau: "Camera góc rộng: 50MP, f/1.8, PDAF Camera macro: 2 MP, f/2.4 Camera đo độ sâu: 2 MP, f/2.4",
    cameraTruoc: "13 MP, f/2.0",
    loaiCPU: "Exynos 1330 (5nm)",
    chipsetVaGPU: "Chipset",
    chip: "Mali-G68 MP2",
    congNgheSac: "Sạc nhanh 25 W",
    theSim: "2 SIM (Nano-SIM)",
    hoTroMang: "5G",
    wifi: "802.11 a/b/g/n/ac",
    bluetooth: "Bluetooth v5.2",
    gps: "GPS, GLONASS, GALILEO, BDS, QZSS, NavIC",
    kichThuoc: "166.8 x 77.2 x 9.4 mm",
    trongLuong: "206 g",
    chatLieuMatLung: "Nhựa",
    chatLieuKhungVien: "Nhựa",
}

let sp20 = {
    masp: 20,
    tensp: 'Samsung Galaxy Z Flip5 512GB',
    tensp1: 'Samsung Galaxy Z Flip5 512GB',
    tensp2: 'Samsung Galaxy Z Flip5 512GB',
    hinhanh: '../images/SamSung/samsung-galaxy-zflip5-xanh-256gb-1.png',
    hinhanh1: '../images/SamSung/samsung-galaxy-zflip5-xanh-256gb-2.png',
    hinhanh2: '../images/SamSung/samsung-galaxy-zflip5-xanh-256gb-3.png',
    hinhanh3: '../images/SamSung/samsung-galaxy-zflip5-xanh-256gb-1.png',
    hinhanh4: '../images/SamSung/samsung-galaxy-zflip5-xanh-256gb-2.png',
    hinhanh5: '../images/SamSung/samsung-galaxy-zflip5-xanh-256gb-3.png',
    hinhanh6: '../images/SamSung/Samsung_Galaxy_Z_Flip5-removebg-preview.png',
    soDanhGia: "Không có đánh giá",
    loaiPhienBan: "512GB",
    giaHienTai: "17.490.000₫",
    giaHienTai1: "17.490.000₫",
    giaGiam: "29.990.000₫",
    mauSac: 'Xanh lá',
    kichThuocManHinh: '6.7"',
    kichThuocManHinh1: '6.7"',
    congNgheManHinh: "Dynamic AMOLED 2X",
    congNgheManHinh1: "Dynamic AMOLED 2X",
    dungLuongRam: "8 GB",
    dungLuongRam1: "8 GB",
    boNhoTrong: "512 GB",
    boNhoTrong1: "512 GB",
    pin: "3700 mAh",
    pin1: "3700 mAh",
    heDieuHanh: "Android 13",
    heDieuHanh1: "Android 13",
    doPhanGiaiManHinh: "1080 x 2640 pixels",
    tanSoQuet: "120Hz",
    kieuManHinh: "Màn hình gập",
    cameraSau: "Camera siêu rộng: 12MP, F2.2 Camera chính: 12MP, F1.8",
    cameraTruoc: "10MP, F2.4",
    loaiCPU: "Snapdragon 8 Gen 2 for Galaxy",
    chipsetVaGPU: "Chipset",
    chip: "Adreno 740",
    congNgheSac: "Sạc tối đa: 25W",
    theSim: "Nano-SIM + eSIM",
    hoTroMang: "5G",
    wifi: "Dual-band (2.4 GHz/5 GHz)",
    bluetooth: "Bluetooth v5.3",
    gps: "GLONASS, GPS, GALILEO, QZSS, BEIDOU",
    kichThuoc: "Mở: 165.1 x 71.9 x 6.9mm Gập: 85.1 x 71.9 x 15.1mm",
    trongLuong: "187g",
    chatLieuMatLung: "Kính",
    chatLieuKhungVien: "Kim loại",
}

let sp21 = {
    masp: 21,
    tensp: 'OPPO Reno11 F 5G 8GB 256GB | Chính hãng VN/A',
    tensp1: 'OPPO Reno11 F 5G 8GB 256GB | Chính hãng VN/A',
    tensp2: 'OPPO Reno11 F 5G 8GB 256GB | Chính hãng VN/A',
    hinhanh: '../images/Oppo/oppoTim_1.png',
    hinhanh1: '../images/Oppo/oppoTim_2.png',
    hinhanh2: '../images/Oppo/oppoTim_3.png',
    hinhanh3: '../images/Oppo/oppoTim_1.png',
    hinhanh4: '../images/Oppo/oppoTim_2.png',
    hinhanh5: '../images/Oppo/oppoTim_3.png',
    hinhanh6: '../images/Oppo/oppoRenoTimleft-removebg-preview.png',
    soDanhGia: "12 đánh giá",
    loaiPhienBan: "256 GB",
    giaHienTai: "8.390.000₫",
    giaHienTai1: "8.390.000₫",
    giaGiam: "8.990.000₫",
    mauSac: "Tím 5G",
    kichThuocManHinh: '6.7"',
    kichThuocManHinh1: '6.7"',
    congNgheManHinh: "AMOLED",
    congNgheManHinh1: "AMOLED",
    dungLuongRam: "8GB",
    dungLuongRam1: "8GB",
    boNhoTrong: "256GB",
    boNhoTrong1: "256GB",
    pin: "5000 mAh",
    pin1: "5000 mAh",
    heDieuHanh: "ColorOS 14 Android 14 - Thuật toán tối ưu hiệu năng",
    heDieuHanh1: "ColorOS 14 Android 14 - Thuật toán tối ưu hiệu năng",
    doPhanGiaiManHinh: "1080 x 2412 pixels",
    tanSoQuet: "120Hz",
    kieuManHinh: "Đục lỗ (Nốt ruồi)",
    cameraSau: "Camera góc rộng: 64 MP, f/1.7; Camera góc siêu rộng: 8 MP, f/2.2; Camera macro: 2 MP, f/2.4",
    cameraTruoc: "Camera góc rộng: 32 MP, f/2.4, 22mm, 1/2.74', 0.8µm",
    loaiCPU: "Octa-core (2x2.6 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55)",
    chipsetVaGPU: "Chipset",
    chip: "Mediatek Dimensity 7050 (6 nm)",
    congNgheSac: "Sạc nhanh 67W",
    theSim: "2 SIM (Nano-SIM)",
    hoTroMang: "5G",
    wifi: "802.11 a/b/g/n/ac/6",
    kichThuoc: "161.1 x 74.7 x 7.5 mm",
    trongLuong: "178g",
    chatLieuKhungVien: "Nhựa",
    chatLieuMatLung: "Nhựa",
}

let sp22 = {
    masp: 22,
    tensp: 'OPPO Reno10 5G 8GB 256GB | Chính hãng VN/A',
    tensp1: 'OPPO Reno10 5G 8GB 256GB | Chính hãng VN/A',
    tensp2: 'OPPO Reno10 5G 8GB 256GB | Chính hãng VN/A',
    hinhanh: '../images/Oppo/oppo-reno10-xanh-1.png',
    hinhanh1: '../images/Oppo/oppo-reno10-xanh-2.png',
    hinhanh2: '../images/Oppo/oppo-reno10-xanh-3.png',
    hinhanh3: '../images/Oppo/oppo-reno10-xanh-1.png',
    hinhanh4: '../images/Oppo/oppo-reno10-xanh-2.png',
    hinhanh5: '../images/Oppo/oppo-reno10-xanh-3.png',
    hinhanh6: '../images/Oppo/oppoReno10-removebg-preview.png',
    soDanhGia: "2 đánh giá",
    loaiPhienBan: "256 GB",
    giaHienTai: "8.790.000đ",
    giaHienTai1: "8.790.000đ",
    giaGiam: "10.990.000đ",
    mauSac: "Xanh",
    kichThuocManHinh: '6.7"',
    kichThuocManHinh1: '6.7"',
    congNgheManHinh: "AMOLED",
    congNgheManHinh1: "AMOLED",
    dungLuongRam: "8 GB",
    dungLuongRam1: "8 GB",
    boNhoTrong: "256 GB",
    boNhoTrong1: "256 GB",
    pin: "5000 mAh",
    pin1: "5000 mAh",
    heDieuHanh: "Android 13",
    heDieuHanh1: "Android 13",
    doPhanGiaiManHinh: "1080 x 2412 pixels",
    tanSoQuet: "120Hz",
    kieuManHinh: "Đục lỗ (Nốt ruồi)",
    cameraSau: "Camera góc rộng: 64MP; f/1.7, PDAF\nChụp Telephoto chân dung: 32 MP, f/2.0\nCamera góc siêu rộng: 8 MP, f/2.2, Zoom quang lai 2X× và Xoom kỹ thuật số 20X",
    cameraTruoc: "32 MP, f/2.4",
    loaiCPU: "8 cores",
    chipsetVaGPU: "Chipset",
    chip: "MediaTek Dimensity 7050",
    congNgheSac: "Sạc nhanh SUPERVOOCTM 67W\nSUPERVOOCTM 2.0\nSUPERVOOCTM\nVOOC 3.0\nPD3.0（9V/2A）",
    theSim: "2 SIM (Nano-SIM)",
    hoTroMang: "5G",
    wifi: "Wi-Fi MIMO\nWi-Fi 6\nWi-Fi Direct\nWi-Fi hotspot\nDual-band (2.4 GHz/5 GHz)",
    kichThuoc: "162.4 x 74.2 x 7.99 mm",
    trongLuong: "185 g",
    chatLieuKhungVien: "Không có thông tin",
    chatLieuMatLung: "Không có thông tin",
}

let sp23 = {
    masp: 23,
    tensp: 'OPPO A77s 8GB 128GB | Chính hãng VN/A',
    tensp1: 'OPPO A77s 8GB 128GB | Chính hãng VN/A',
    tensp2: 'OPPO A77s 8GB 128GB | Chính hãng VN/A',
    hinhanh: '../images/Oppo/oppo-a77s-den-1.png',
    hinhanh1: '../images/Oppo/oppo-a77s-den-2.png',
    hinhanh2: '../images/Oppo/oppo-a77s-den-3.png',
    hinhanh3: '../images/Oppo/oppo-a77s-den-1.png',
    hinhanh4: '../images/Oppo/oppo-a77s-den-2.png',
    hinhanh5: '../images/Oppo/oppo-a77s-den-3.png',
    hinhanh6: '../images/Oppo/oppoA77s_den-removebg-preview.png',
    giaHienTai: "5.490.000₫",
    giaHienTai1: "5.490.000₫",
    giaGiam: "6.190.000₫",
    loaiPhienBan: "128GB",
    mauSac: "Đen",
    soDanhGia: "50 đánh giá",
    kichThuocManHinh: '6.56"',
    kichThuocManHinh1: '6.56"',
    congNgheManHinh: "IPS LCD",
    congNgheManHinh1: "IPS LCD",
    dungLuongRam: "8 GB",
    dungLuongRam1: "8 GB",
    boNhoTrong: "128 GB",
    boNhoTrong1: "128 GB",
    pin: "5,000mAh",
    pin1: "5,000mAh",
    heDieuHanh: "Android 12",
    heDieuHanh1: "Android 12",
    doPhanGiaiManHinh: "720 x 1612 (HD+)",
    tanSoQuet: "90Hz",
    kieuManHinh: "Giọt nước",
    cameraSau: "Camera góc rộng: 50 MP, f/1.8, PDAF | Camera chân dung: 2 MP, f/2.4",
    cameraTruoc: "8 MP, f/2.0",
    loaiCPU: "4x2.4 GHz Kryo 265 Gold & 4x1.9 GHz Kryo 265 Silver",
    chipsetVaGPU: "Chipset",
    chip: "Snapdragon 680 4G",
    congNgheSac: "Sạc nhanh VOCC 33W",
    theSim: "2 SIM (Nano-SIM)",
    hoTroMang: "4G",
    wifi: "Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, hotspot",
    kichThuoc: "163.8 x 75 x 8 mm",
    trongLuong: "187 g",
    chatLieuKhungVien: "Kính",
    chatLieuMatLung: "Kim loại",
    
}

let sp24 = {
    masp: 24,
    tensp: 'OPPO Find N3 | Chính hãng VN/A',
    tensp1: 'OPPO Find N3 | Chính hãng VN/A',
    tensp2: 'OPPO Find N3 | Chính hãng VN/A',
    hinhanh: '../images/Oppo/oppo-find-n3-vang-1.png',
    hinhanh1: '../images/Oppo/oppo-find-n3-vang-2.png',
    hinhanh2: '../images/Oppo/oppo-find-n3-vang-3.png',
    hinhanh3: '../images/Oppo/oppo-find-n3-vang-1.png',
    hinhanh4: '../images/Oppo/oppo-find-n3-vang-2.png',
    hinhanh5: '../images/Oppo/oppo-find-n3-vang-3.png',
    hinhanh6: '../images/Oppo/OppoFindN3_vang-removebg-preview.png',
    giaHienTai: "36.990.000đ",
    giaHienTai1: "36.990.000đ",
    giaGiam: "41.990.000₫",
    soDanhGia: "50 đánh giá",
    kichThuocManHinh: '7.82"',
    kichThuocManHinh1: '7.82"',
    congNgheManHinh: "OLED",
    congNgheManHinh1: "OLED",
    dungLuongRam: "16 GB",
    dungLuongRam1: "16 GB",
    boNhoTrong: "512 GB",
    boNhoTrong1: "512 GB",
    pin: "4805 mAh",
    pin1: "4805 mAh",
    heDieuHanh: "Android 13",
    heDieuHanh1: "Android 13",
    doPhanGiaiManHinh: "2268 x 2440 pixels",
    tanSoQuet: "120Hz",
    kieuManHinh: "Màn hình gập",
    cameraSau: "Camera chính: 48MP, f/1.7, OIS | Camera góc rộng: 48MP, f/2.2 | Camera Tele: 64MP, f/2.6",
    cameraTruoc: "Màn hình chính: 20MP, f/2.2 | Màn hình ngoài: 32MP, f/2.4",
    loaiCPU: "1x3.2 GHz Cortex-X3 & 2x2.8 GHz Cortex-A715 & 2x2.8 GHz Cortex-A710 & 3x2.0 GHz Cortex-A510",
    chipsetVaGPU: "Chipset",
    chip: "Snapdragon 8 Gen 2 8 nhân",
    congNgheSac: "Sạc nhanh 67W",
    theSim: "Nano-SIM + eSIM",
    hoTroMang: "5G",
    wifi: "802.11 a/b/g/n/ac/6/7",
    kichThuoc: "Màu Vàng: Khi mở: 153.4 x 143.1 x 5.9 (màn hình ngoài)/5.8 (mặt lưng) mm | Khi gập: 153.4 x 73.3 x 11.7 mm, Màu Đen: Khi mở: 153.4 x 143.1 x 5.9 (màn hình ngoài)/6.0 (mặt lưng) mm | Khi gập: 153.4 x 73.3 x 11.9 mm",
    trongLuong: "245 g (kính) | 239 g (da)",
    chatLieuKhungVien: "Nhôm",
    chatLieuMatLung: "IPX4",
    mauSac: "Vàng",
    loaiPhienBan: "512 GB"
}

let sp25 = {
    masp: 25,
    tensp: 'OPPO A58 4G 6GB 128GB | Chính hãng VN/A',
    tensp1: 'OPPO A58 4G 6GB 128GB | Chính hãng VN/A',
    tensp2: 'OPPO A58 4G 6GB 128GB | Chính hãng VN/A',
    hinhanh: '../images/Oppo/oppo-a58-den-1.png',
    hinhanh1: '../images/Oppo/oppo-a58-den-2.png',
    hinhanh2: '../images/Oppo/oppo-a58-den-3.png',
    hinhanh3: '../images/Oppo/oppo-a58-den-1.png',
    hinhanh4: '../images/Oppo/oppo-a58-den-2.png',
    hinhanh5: '../images/Oppo/oppo-a58-den-3.png',
    hinhanh6: '../images/Oppo/OppoA58_den-removebg-preview.png',
    giaHienTai: "4.190.000đ",
    giaHienTai1: "4.190.000đ",
    giaGiam: "4.690.000₫",
    soDanhGia: "50 đánh giá",
    kichThuocManHinh: '6.72"',
    kichThuocManHinh1: '6.72"',
    congNgheManHinh: "IPS LCD",
    congNgheManHinh1: "IPS LCD",
    dungLuongRam: "6 GB",
    dungLuongRam1: "6 GB",
    boNhoTrong: "128 GB",
    boNhoTrong1: "128 GB",
    pin: "5000mAh (Typ)",
    pin1: "5000mAh (Typ)",
    heDieuHanh: "ColorOS 13.1, nền tảng Android 13",
    heDieuHanh1: "ColorOS 13.1, nền tảng Android 13",
    doPhanGiaiManHinh: "1080 x 2400 pixels (FullHD+)",
    tanSoQuet: "60Hz",
    kieuManHinh: "Màn hình phẳng",
    cameraSau: "50 MP,F/1.8 (chính) + 2 MP, F/2.4 (Xóa phông)",
    cameraTruoc: "8 MP, F/2.0",
    loaiCPU: "2x2,2 GHz Cortex-A76 & 6x2,0 GHz Cortex-A55",
    chipsetVaGPU: "Chipset",
    chip: "Helio G85",
    congNgheSac: "Siêu sạc nhanh SUPERVOOC 33W",
    theSim: "2 SIM (Nano-SIM)",
    hoTroMang: "4G",
    wifi: "2.4G/5G, 802.11 a/b/g/n/ac",
    kichThuoc: "165.65 x 75.98 x 7.99 mm",
    trongLuong: "Khoảng 192g (Bao gồm pin)",
    chatLieuKhungVien: "Nhôm",
    chatLieuMatLung: "IP54",
    mauSac: "Đen",
    loaiPhienBan: "128 GB"
}

let sp26 = {
    masp: 26,
    tensp: 'OPPO A78 4G (8GB 256GB) | Chính hãng VN/A',
    tensp1: 'OPPO A78 4G (8GB 256GB) | Chính hãng VN/A',
    tensp2: 'OPPO A78 4G (8GB 256GB) | Chính hãng VN/A',
    hinhanh: '../images/Oppo/oppo-a78-den-1.png',
    hinhanh1: '../images/Oppo/oppo-a78-den-2.png',
    hinhanh2: '../images/Oppo/oppo-a78-den-3.png',
    hinhanh3: '../images/Oppo/oppo-a78-den-1.png',
    hinhanh4: '../images/Oppo/oppo-a78-den-2.png',
    hinhanh5: '../images/Oppo/oppo-a78-den-3.png',
    hinhanh6: '../images/Oppo/OppoA78_den-removebg-preview.png',
    giaHienTai: "5.490.000đ",
    giaHienTai1: "5.490.000đ",
    giaGiam: "6.490.000₫",
    soDanhGia: "55 đánh giá",
    kichThuocManHinh: '6.43"',
    kichThuocManHinh1: '6.43"',
    congNgheManHinh: "AMOLED",
    congNgheManHinh1: "AMOLED",
    dungLuongRam: "8 GB",
    dungLuongRam1: "8 GB",
    boNhoTrong: "256 GB",
    boNhoTrong1: "256 GB",
    pin: "5000 mAh",
    pin1: "5000 mAh",
    heDieuHanh: "ColorOS 13.1.1, nền tảng Android 13",
    heDieuHanh1: "ColorOS 13.1.1, nền tảng Android 13",
    doPhanGiaiManHinh: "1080 x 2400 pixels (FullHD+)",
    tanSoQuet: "90Hz",
    kieuManHinh: "Đục lỗ (Nốt ruồi)",
    cameraSau: "50 MP (chính) + 2 MP (Xóa phông)",
    cameraTruoc: "8 MP",
    loaiCPU: "4 nhân 2.4 GHz & 4 nhân 1.9 GHz",
    chipsetVaGPU: "Chipset",
    chip: "Qualcomm Snapdragon 680",
    congNgheSac: "Siêu sạc nhanh SUPERVOOC 67W , tiết kiệm pin",
    theSim: "2 SIM (Nano-SIM)",
    hoTroMang: "4G",
    wifi: "Dual-band (2.4 GHz/5 GHz), Wi-Fi 802.11 a/b/g/n/ac",
    kichThuoc: "Đen: 160 x 73.23 x 7.93 mm | Xanh: 160 x 73.23 x 7.99 mm",
    trongLuong: "180g",
    chatLieuMatLung: "IP54",
    mauSac: "Xanh",
    chatLieuKhungVien: "Nhựa",
    loaiPhienBan: "256 GB"
}


let sp27 = {
    masp: 27,
    tensp: 'OPPO A17K | Chính hãng VN/A',
    tensp1: 'OPPO A17K | Chính hãng VN/A',
    tensp2: 'OPPO A17K | Chính hãng VN/A',
    hinhanh: '../images/Oppo/oppo-a17k-vang-1.png',
    hinhanh1: '../images/Oppo/oppo-a17k-vang-2.png',
    hinhanh2: '../images/Oppo/oppo-a17k-vang-3.png',
    hinhanh3: '../images/Oppo/oppo-a17k-vang-1.png',
    hinhanh4: '../images/Oppo/oppo-a17k-vang-2.png',
    hinhanh5: '../images/Oppo/oppo-a17k-vang-3.png',
    hinhanh6: '../images/Oppo/OppoA17k_Vang-removebg-preview.png',
    giaHienTai: "2.790.000đ",
    giaHienTai1: "2.790.000đ",
    giaGiam: "3.290.000₫",
    soDanhGia: "52 đánh giá",
    kichThuocManHinh: '6.56"',
    kichThuocManHinh1: '6.56"',
    congNgheManHinh: "IPS LCD",
    congNgheManHinh1: "IPS LCD",
    dungLuongRam: "3 GB",
    dungLuongRam1: "3 GB",
    boNhoTrong: "64 GB",
    boNhoTrong1: "64 GB",
    pin: "5000 mAh",
    pin1: "5000 mAh",
    heDieuHanh: "Android 12",
    heDieuHanh1: "Android 12",
    doPhanGiaiManHinh: "720 x 1612 (HD+)",
    tanSoQuet: "60Hz",
    kieuManHinh: "Mặt kính cảm ứng: Kính cường lực Panda",
    cameraSau: "8 MP, f/2.0, FOV 78°",
    cameraTruoc: "5MP (f/2.2); FOV 76.8°",
    loaiCPU: "8 nhân, lên đến 2.3GHz",
    chipsetVaGPU: "Chipset",
    chip: "MediaTek Helio G35",
    congNgheSac: "Sạc 10 W",
    theSim: "2 SIM (Nano-SIM)",
    hoTroMang: "4G",
    wifi: "Wi-Fi 5 (802.11ac), 802.11a/b/g/n",
    kichThuoc: "164.2 x 75.6 x 8.3 mm",
    trongLuong: "189g",
    chatLieuMatLung: "Nhựa",
    chatLieuKhungVien: "Nhựa",
    mauSac: "Vàng",
    loaiPhienBan: "64 GB"
}

let sp28 = {
    masp: 28,
    tensp: 'OPPO Reno7 5G (8GB 256GB) | Chính hãng VN/A',
    tensp1: 'OPPO Reno7 5G (8GB 256GB) | Chính hãng VN/A',
    tensp2: 'OPPO Reno7 5G (8GB 256GB) | Chính hãng VN/A',
    hinhanh: '../images/Oppo/oppo-reno7-1.png',
    hinhanh1: '../images/Oppo/oppo-reno7-2.png',
    hinhanh2: '../images/Oppo/oppo-reno7-3.png',
    hinhanh3: '../images/Oppo/oppo-reno7-1.png',
    hinhanh4: '../images/Oppo/oppo-reno7-2.png',
    hinhanh5: '../images/Oppo/oppo-reno7-3.png',
    hinhanh6: '../images/Oppo/OppoReno7_Xanh-removebg-preview.png',
    giaHienTai: "7.590.000đ",
    giaHienTai1: "7.590.000₫",
    giaGiam: "7.090.000đ",
    soDanhGia: "50 đánh giá",
    kichThuocManHinh: '6.4"',
    kichThuocManHinh1: '6.4"',
    congNgheManHinh: "AMOLED",
    congNgheManHinh1: "AMOLED",
    dungLuongRam: "8 GB",
    dungLuongRam1: "8 GB",
    boNhoTrong: "256 GB",
    boNhoTrong1: "256 GB",
    pin: "Li-Po 4500 mAh",
    pin1: "Li-Po 4500 mAh",
    heDieuHanh: "Android",
    heDieuHanh1: "Android",
    doPhanGiaiManHinh: "1080 x 2400 pixels (FullHD+)",
    tanSoQuet: "90Hz",
    kieuManHinh: "Đục lỗ (Nốt ruồi)",
    cameraSau: "AI Camera",
    cameraTruoc: "32MP f/2.4",
    loaiCPU: "4x2.4 GHz Kryo 670 & 4x1.9 GHz Kryo 670",
    chipsetVaGPU: "Chipset",
    chip: "MediaTek Dimensity 900",
    congNgheSac: "Sạc nhanh 65W",
    theSim: "2 SIM (Nano-SIM)",
    hoTroMang: "5G",
    wifi: "Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct, hotspot",
    kichThuoc: "160.6 x 73.2 x 7.81 mm",
    trongLuong: "173 g",
    chatLieuMatLung: "Nhựa",
    chatLieuKhungVien: "Nhựa",
    mauSac: "Xanh",
    loaiPhienBan: "256 GB"
}

let sp29 = {
    masp: 29,
    tensp: 'OPPO Find N3 Flip 12GB 256GB | Chính hãng VN/A',
    tensp1: 'OPPO Find N3 Flip 12GB 256GB | Chính hãng VN/A',
    tensp2: 'OPPO Find N3 Flip 12GB 256GB | Chính hãng VN/A',
    hinhanh: '../images/Oppo/oppo-n3-flip-vang-1.png',
    hinhanh1: '../images/Oppo/oppo-n3-flip-vang-2.png',
    hinhanh2: '../images/Oppo/oppo-n3-flip-vang-3.png',
    hinhanh3: '../images/Oppo/oppo-n3-flip-vang-1.png',
    hinhanh4: '../images/Oppo/oppo-n3-flip-vang-2.png',
    hinhanh5: '../images/Oppo/oppo-n3-flip-vang-3.png',
    hinhanh6: '../images/Oppo/OppoFindN3Flip_vang-removebg-preview.png',
    giaHienTai: "19.990.000đ",
    giaHienTai1: "19.990.000đ",
    giaGiam: "22.990.000₫",
    soDanhGia: "50 đánh giá",
    kichThuocManHinh: '6.8"',
    kichThuocManHinh1: '6.8"',
    congNgheManHinh: "AMOLED",
    congNgheManHinh1: "AMOLED",
    dungLuongRam: "12 GB",
    dungLuongRam1: "12 GB",
    boNhoTrong: "256 GB",
    boNhoTrong1: "256 GB",
    pin: "Li-Po 4300 mAh",
    pin1: "Li-Po 4300 mAh",
    heDieuHanh: "Android 13",
    heDieuHanh1: "Android 13",
    doPhanGiaiManHinh: "1080 x 2520 pixels",
    tanSoQuet: "120Hz",
    kieuManHinh: "Màn hình gập",
    cameraSau: "AI Camera",
    cameraTruoc: "32 MP, f/2.4",
    loaiCPU: "1 nhân 3.05 GHz, 3 nhân 2.85 GHz & 4 nhân 1.8 GHz",
    chipsetVaGPU: "Chipset",
    chip: "MediaTek Dimensity 9200",
    congNgheSac: "Sạc nhanh SuperVOOC 3.0 công suất 44 W",
    theSim: "2 SIM (Nano-SIM)",
    hoTroMang: "5G",
    wifi: "Wi-Fi 6, Wi-Fi 802.11 a/b/g/n/ac, Wi-Fi 802.11 a/b/g/n, Dual-band (2.4 GHz/5 GHz), Wi-Fi 7 5.8 GHz",
    kichThuoc: "Khi mở: 166.42 x 75.78 x 7.79 mm; Khi gập: 85.54 x 75.78 x 16.45 mm",
    trongLuong: "198 g",
    chatLieuMatLung: "Kính",
    chatLieuKhungVien: "Nhôm",
    mauSac: "Vàng",
    loaiPhienBan: "256 GB"
}

let sp30 = {
    masp: 30,
    tensp: 'OPPO Reno8 T 4G 256GB | Chính hãng VN/A',
    tensp1: 'OPPO Reno8 T 4G 256GB | Chính hãng VN/A',
    tensp2: 'OPPO Reno8 T 4G 256GB | Chính hãng VN/A',
    hinhanh: '../images/Oppo/oppo-reno8-t-den-1.png',
    hinhanh1: '../images/Oppo/oppo-reno8-t-den-2.png',
    hinhanh2: '../images/Oppo/oppo-reno8-t-den-3.png',
    hinhanh3: '../images/Oppo/oppo-reno8-t-den-1.png',
    hinhanh4: '../images/Oppo/oppo-reno8-t-den-2.png',
    hinhanh5: '../images/Oppo/oppo-reno8-t-den-3.png',
    hinhanh6: '../images/Oppo/OPPOReno8T_Den-removebg-preview.png',
    giaHienTai: "6.690.000đ",
    giaHienTai1: "6.690.000đ",
    giaGiam: "7.190.000₫",
    soDanhGia: "Chưa có đánh giá",
    kichThuocManHinh: '6.4"',
    kichThuocManHinh1: '6.4"',
    kieuManHinh: "Giọt nước",
    congNgheManHinh: "AMOLED",
    congNgheManHinh1: "AMOLED",
    doPhanGiaiManHinh: "1080 x 2400 pixels (FullHD+)",
    tanSoQuet: "90Hz",
    cameraSau: "100MP (Chính) + 2MP (Kính hiển vi) + 2MP (Mono)",
    cameraTruoc: "32MP",
    loaiCPU: "Helio G99, tối đa 2.2GHz",
    chipsetVaGPU: "Chipset",
    chip: "MediaTek Dimensity 9200",
    dungLuongRam: "8 GB",
    dungLuongRam1: "8 GB",
    boNhoTrong: "256 GB",
    hoTroMang: "5G",
    boNhoTrong1: "256 GB",
    pin: "5000mAh (Typ)",
    pin1: "5000mAh (Typ)",
    congNgheSac: "Siêu sạc nhanh superVOOC 33W",
    theSim: "2 SIM (Nano-SIM)",
    heDieuHanh: "ColorOS 13, nền tảng Android 13",
    heDieuHanh1: "ColorOS 13, nền tảng Android 13",
    wifi: "Wifi 2.4G/5G, 802.11 a/b/g/n/ac",
    kichThuoc: "Cam: 160.8 x 73.8 x 7.85 mm; Đen: 160.8 x 73.8 x 7.8 mm",
    trongLuong: "Cam: Khoảng 182.5g (Bao gồm pin); Đen: Khoảng 179.5g (Bao gồm pin)",
    mauSac: "Vàng",
    loaiPhienBan: "256 GB",
    chatLieuMatLung: "Kính",
    chatLieuKhungVien: "Nhôm",
}

let sp31 = {
    masp: 31,
    tensp: 'Xiaomi 14 (12GB 256GB) | Chính hãng VN/A',
    tensp1: 'Xiaomi 14 (12GB 256GB) | Chính hãng VN/A',
    tensp2: 'Xiaomi 14 (12GB 256GB) | Chính hãng VN/A',
    hinhanh: '../images/Xiaomi/xiaomi14_XanhLa_1.jpg',
    hinhanh1: '../images/Xiaomi/xiaomi14_XanhLa_2.jpg',
    hinhanh2: '../images/Xiaomi/xiaomi14_XanhLa_3.jpg',
    hinhanh3: '../images/Xiaomi/xiaomi14_XanhLa_1.jpg',
    hinhanh4: '../images/Xiaomi/xiaomi14_XanhLa_2.jpg',
    hinhanh5: '../images/Xiaomi/xiaomi14_XanhLa_3.jpg',
    hinhanh6: '../images/Xiaomi/xiaomi14_XanhLa-removebg-preview.png',
    soDanhGia: "150 đánh giá",
    loaiPhienBan: "256GB",
    giaHienTai: "20.990.000đ",
    giaHienTai1: "20.990.000đ",
    giaGiam: "22.990.000đ",
    mauSac: 'Xanh',
    kichThuocManHinh: '6.36"',
    kichThuocManHinh1: '6.36"',
    congNgheManHinh: "LTPO OLED",
    congNgheManHinh1: "LTPO OLED",
    dungLuongRam: "12 GB",
    dungLuongRam1: "12 GB",
    boNhoTrong: "256 GB",
    boNhoTrong1: "256 GB",
    pin: "4610 mAh",
    pin1: "4610 mAh",
    heDieuHanh: "Android 14",
    heDieuHanh1: "Android 14",
    doPhanGiaiManHinh: "1200 x 2670 pixels",
    tanSoQuet: "120Hz",
    kieuManHinh: 'Đục lỗ (Nốt ruồi)',
    cameraSau: "Camera góc rộng: 50 MP, f/1.6, 23mm, 2.4µm, PDAF, OIS\nCamera chụp xa: 50 MP, f/1.9, 50mm, 1/2.88\", 0.61µm, PDAF, 2x optical zoom\nCamera góc siêu rộng: 50 MP, f/1.8, 12mm, 122˚, 1/2.51\", PDAF",
    cameraTruoc: "Camera góc rộng: 50 MP, f/ 2.2, PDAF",
    loaiCPU: "Qualcomm Snapdragon 8 Gen 3 (4 nm)",
    chipsetVaGPU: "Chipset",
    chip: "Qualcomm Snapdragon 8 Gen 3 (4 nm)",
    congNgheSac: "Sạc có dây 90W, PD3.0, QC4\nSạc không dây 50W\nSạc không dây đảo ngược 10W",
    theSim: "2 SIM (Nano-SIM)",
    hoTroMang: "5G",
    wifi: "802.11 a/b/g/n/ac/6e",
    kichThuoc: "152.8 x 71.5 x 8.2 mm",
    trongLuong: "193 g",
    chatLieuKhungVien: "Không có thông tin",
    chatLieuMatLung: "Không có thông tin",
}

let sp32 = {
    masp: 32,
    tensp: 'Xiaomi Redmi Note 13 Pro 4G | Chính hãng VN/A',
    tensp1: 'Xiaomi Redmi Note 13 Pro 4G | Chính hãng VN/A',
    tensp2: 'Xiaomi Redmi Note 13 Pro 4G | Chính hãng VN/A',
    hinhanh: '../images/Xiaomi/xiaomi_redmi_note_13_pro_4g_den_1.png',
    hinhanh1: '../images/Xiaomi/xiaomi_redmi_note_13_pro_4g_den_2.png',
    hinhanh2: '../images/Xiaomi/xiaomi_redmi_note_13_pro_4g_den_3.png',
    hinhanh3: '../images/Xiaomi/xiaomi_redmi_note_13_pro_4g_den_1.png',
    hinhanh4: '../images/Xiaomi/xiaomi_redmi_note_13_pro_4g_den_2.png',
    hinhanh5: '../images/Xiaomi/xiaomi_redmi_note_13_pro_4g_den_3.png',
    hinhanh6: '../images/Xiaomi/xiaomi_redmi_note_13_pro_4g_den-removebg-preview.png',
    soDanhGia: "125 đánh giá",
    loaiPhienBan: "128GB",
    giaHienTai: "6.890.000₫",
    giaHienTai1: "6.890.000₫",
    giaGiam: "7.290.000₫",
    mauSac: 'Đen',
    kichThuocManHinh: '6.67"',
    kichThuocManHinh1: '6.67"',
    congNgheManHinh: "AMOLED",
    congNgheManHinh1: "AMOLED",
    dungLuongRam: "8 GB",
    dungLuongRam1: "8 GB",
    boNhoTrong: "128 GB",
    boNhoTrong1: "128 GB",
    pin: "5000 mAh",
    pin1: "5000 mAh",
    heDieuHanh: "Android 13",
    heDieuHanh1: "Android 13",
    doPhanGiaiManHinh: "1080 x 2400 pixels (FullHD+)",
    tanSoQuet: "120Hz",
    kieuManHinh: 'Không có thông tin',
    cameraSau: "Chính 200 MP & Phụ 8 MP, 2 MP",
    cameraTruoc: "16 MP",
    loaiCPU: "MediaTek Helio G99-Ultra 8 nhân",
    chipsetVaGPU: "Chipset",
    chip: "MediaTek Helio G99-Ultra 8 nhân",
    congNgheSac: "Sạc nhanh 67 W",
    theSim: "2 SIM (Nano-SIM)",
    hoTroMang: "4G",
    wifi: "Wi-Fi hotspot\nWi-Fi 802.11 a/b/g/n/ac\nDual-band (2.4 GHz/5 GHz)",
    kichThuoc: "161.1 x 74.95 x 7.98 mm",
    trongLuong: "188 g",
    chatLieuKhungVien: "Nhựa",
    chatLieuMatLung: "Nhựa",
}

let sp33 = {
    masp: 33,
    tensp: 'Xiaomi Redmi Note 12 8GB 128GB | Chính hãng VN/A',
    tensp1: 'Xiaomi Redmi Note 12 8GB 128GB | Chính hãng VN/A',
    tensp2: 'Xiaomi Redmi Note 12 8GB 128GB | Chính hãng VN/A',
    hinhanh: '../images/Xiaomi/xiaomi-redmi-note-12-xanh-la-1.png',
    hinhanh1: '../images/Xiaomi/xiaomi-redmi-note-12-xanh-la-2.png',
    hinhanh2: '../images/Xiaomi/xiaomi-redmi-note-12-xanh-la-3.png',
    hinhanh3: '../images/Xiaomi/xiaomi-redmi-note-12-xanh-la-1.png',
    hinhanh4: '../images/Xiaomi/xiaomi-redmi-note-12-xanh-la-2.png',
    hinhanh5: '../images/Xiaomi/xiaomi-redmi-note-12-xanh-la-3.png',
    hinhanh6: '../images/Xiaomi/xiaomi_redmi_note_12_8GB_xanhla-removebg-preview.png',
    soDanhGia: "115",
    loaiPhienBan: "128GB",
    giaHienTai: "4.290.000đ",
    giaHienTai1: "4.290.000đ",
    giaGiam: "5.790.000đ",
    mauSac: 'Xanh lá',
    kichThuocManHinh: '6.67"',
    kichThuocManHinh1: '6.67"',
    congNgheManHinh: "AMOLED",
    congNgheManHinh1: "AMOLED",
    dungLuongRam: "8 GB",
    dungLuongRam1: "8 GB",
    boNhoTrong: "128 GB",
    boNhoTrong1: "128 GB",
    pin: "5000mAh",
    pin1: "5000mAh",
    heDieuHanh: "Android 12",
    heDieuHanh1: "Android 12",
    doPhanGiaiManHinh: "1080 x 2400 pixels (FullHD+)",
    tanSoQuet: "120Hz",
    kieuManHinh: 'Đục lỗ (Nốt ruồi)',
    cameraSau: "Camera chính: 50MP, f/1.8\nCamera góc rộng: 8MP, f/2.2, 120°\nCamera Macro: 2MP, f/2.4",
    cameraTruoc: "13MP, f/2.45",
    loaiCPU: "Qualcomm Snapdragon 685\n2X Cortex-A78 @ 2.0GHz ; 6X Cortex-A55 @ 1.8GHz",
    chipsetVaGPU: "Chipset",
    chip: "Qualcomm Snapdragon 685",
    congNgheSac: "Sạc nhanh 33W",
    theSim: "2 SIM (Nano-SIM)",
    hoTroMang: "4G",
    wifi: "802.11 a/b/g/n/ac",
    kichThuoc: "165.66 x 75.96 x 7.85 mm",
    trongLuong: "183.5 g",
    chatLieuKhungVien: "Không có thông tin",
    chatLieuMatLung: "Không có thông tin",
}

let sp34 = {
    masp: 34,
    tensp: 'Xiaomi Redmi Note 13 6GB 128GB | Chính hãng VN/A',
    tensp1: 'Xiaomi Redmi Note 13 6GB 128GB | Chính hãng VN/A',
    tensp2: 'Xiaomi Redmi Note 13 6GB 128GB | Chính hãng VN/A',
    hinhanh: '../images/Xiaomi/xiaomi-redmi-note-13-den_1.png',
    hinhanh1: '../images/Xiaomi/xiaomi-redmi-note-13-den_2.png',
    hinhanh2: '../images/Xiaomi/xiaomi-redmi-note-13-den_3.png',
    hinhanh3: '../images/Xiaomi/xiaomi-redmi-note-13-den_1.png',
    hinhanh4: '../images/Xiaomi/xiaomi-redmi-note-13-den_2.png',
    hinhanh5: '../images/Xiaomi/xiaomi-redmi-note-13-den_3.png',
    hinhanh6: '../images/Xiaomi/xiaomi-redmi-note-13-den-removebg-preview.png',
    soDanhGia: "135 đánh giá",
    loaiPhienBan: "128GB",
    giaHienTai: "4.690.000đ",
    giaHienTai1: "4.690.000đ",
    giaGiam: "4.890.000đ",
    mauSac: 'Đen',
    kichThuocManHinh: '6.67"',
    kichThuocManHinh1: '6.67"',
    congNgheManHinh: "AMOLED",
    congNgheManHinh1: "AMOLED",
    dungLuongRam: "6 GB",
    dungLuongRam1: "6 GB",
    boNhoTrong: "128 GB",
    boNhoTrong1: "128 GB",
    pin: "5000 mAh",
    pin1: "5000 mAh",
    heDieuHanh: "Android 13",
    heDieuHanh1: "Android 13",
    doPhanGiaiManHinh: "1080 x 2400 pixels (FullHD+)",
    tanSoQuet: "120Hz",
    kieuManHinh: 'Đục lỗ (Nốt ruồi)',
    cameraSau: "Chính 108 MP & Phụ 8 MP, 2 MP",
    cameraTruoc: "16MP",
    loaiCPU: "Snapdragon 685\nCPU lõi tám, tốc độ lên tới 2,8 GHz",
    chipsetVaGPU: "Chipset",
    chip: "Snapdragon 685",
    congNgheSac: "Sạc nhanh 33W",
    theSim: "2 SIM (Nano-SIM)",
    hoTroMang: "4G",
    wifi: "Wi-Fi Direct\nWi-Fi 802.11 a/b/g/n/ac\nWi-Fi hotspot\nDual-band (2.4 GHz/5 GHz)",
    kichThuoc: "162.24 x 75.55 x 7.97mm",
    trongLuong: "188.5 g",
    chatLieuKhungVien: "Không có thông tin",
    chatLieuMatLung: "Không có thông tin",
}

let sp35 = {
    masp: 35,
    tensp: 'Xiaomi 13T Pro 5G (12GB - 512GB) | Chính hãng VN/A',
    tensp1: 'Xiaomi 13T Pro 5G (12GB - 512GB) | Chính hãng VN/A',
    tensp2: 'Xiaomi 13T Pro 5G (12GB - 512GB) | Chính hãng VN/A',
    hinhanh: '../images/Xiaomi/xiaomi_13T_xanhLa_1.png',
    hinhanh1: '../images/Xiaomi/xiaomi_13T_xanhLa_2.png',
    hinhanh2: '../images/Xiaomi/xiaomi_13T_xanhLa_3.png',
    hinhanh3: '../images/Xiaomi/xiaomi_13T_xanhLa_1.png',
    hinhanh4: '../images/Xiaomi/xiaomi_13T_xanhLa_2.png',
    hinhanh5: '../images/Xiaomi/xiaomi_13T_xanhLa_3.png',
    hinhanh6: '../images/Xiaomi/xiaomi_13T_xanhLa-removebg-preview.png',
    soDanhGia: "160 đánh giá",
    loaiPhienBan: "512GB",
    giaHienTai: "14.790.000đ",
    giaHienTai1: "14.790.000đ",
    giaGiam: "16.990.000đ",
    mauSac: 'Xanh lá',
    kichThuocManHinh: '6.67"',
    kichThuocManHinh1: '6.67"',
    congNgheManHinh: "AMOLED",
    congNgheManHinh1: "AMOLED",
    dungLuongRam: "12 GB",
    dungLuongRam1: "12 GB",
    boNhoTrong: "512 GB",
    boNhoTrong1: "512 GB",
    pin: "5.000 mAh",
    pin1: "5.000 mAh",
    heDieuHanh: "Android 13",
    heDieuHanh1: "Android 13",
    doPhanGiaiManHinh: "1220 x 2712 pixels",
    tanSoQuet: "Từ 144Hz trở lên",
    kieuManHinh: 'Đục lỗ (Nốt ruồi)',
    cameraSau: "Camera chính góc rộng: 50 MP, 1/1.22\"\nCamera góc siêu rộng: 12 MP\nCamera Tele: 50 MP",
    cameraTruoc: "20 MP, f/2,2",
    loaiCPU: "MediaTek Dimensity 9200+\n1x Arm Cortex-X3, lên đến 3,35GHz\n3x Arm Cortex-A715, lên đến 3,0GHz\n4x Arm Cortex-A510, lên đến 2,0GHz",
    chipsetVaGPU: "Chipset",
    chip: "MediaTek Dimensity 9200+",
    congNgheSac: "Sạc nhanh 120 W",
    theSim: "2 Nano SIM hoặc 1 Nano + 1 eSIM",
    hoTroMang: "5G",
    wifi: "2,4 GHz/Wi-Fi 5GHz\nWi-Fi 6",
    kichThuoc: "Kính: 162,2mm x 75,7mm x 8,49mm\nPU: 162,2mm x 75,7mm x 8,62mm",
    trongLuong: "Kính: 206g\nPU: 200g",
    chatLieuKhungVien: "Không có thông tin",
    chatLieuMatLung: "Không có thông tin",
}

let sp36 = {
    masp: 36,
    tensp: 'Xiaomi 12T 8GB 128GB | Chính hãng VN/A',
    tensp1: 'Xiaomi 12T 8GB 128GB | Chính hãng VN/A',
    tensp2: 'Xiaomi 12T 8GB 128GB | Chính hãng VN/A',
    hinhanh: '../images/Xiaomi/xiaomi_12T_pro_bac_1.png',
    hinhanh1: '../images/Xiaomi/xiaomi_12T_pro_bac_2.png',
    hinhanh2: '../images/Xiaomi/xiaomi_12T_pro_bac_3.png',
    hinhanh3: '../images/Xiaomi/xiaomi_12T_pro_bac_1.png',
    hinhanh4: '../images/Xiaomi/xiaomi_12T_pro_bac_2.png',
    hinhanh5: '../images/Xiaomi/xiaomi_12T_pro_bac_3.png',
    hinhanh6: '../images/Xiaomi/xiaomi_12T_pro_bac-removebg-preview.png',
    soDanhGia: "Không có đánh giá",
    loaiPhienBan: "128GB",
    giaHienTai: "8.990.000₫",
    giaHienTai1: "8.990.000₫",
    giaGiam: "12.490.000₫",
    mauSac: 'Bạc',
    kichThuocManHinh: '6.67"',
    kichThuocManHinh1: '6.67"',
    congNgheManHinh: "AMOLED",
    congNgheManHinh1: "AMOLED",
    dungLuongRam: "8 GB",
    dungLuongRam1: "8 GB",
    boNhoTrong: "128 GB",
    boNhoTrong1: "128 GB",
    pin: "5000mAh",
    pin1: "5000mAh",
    heDieuHanh: "Android 12, MIUI 13",
    heDieuHanh1: "Android 12, MIUI 13",
    doPhanGiaiManHinh: "1220 x 2712 pixels",
    tanSoQuet: "120Hz",
    kieuManHinh: "Đục lỗ (Nốt ruồi)",
    cameraSau: "108MP + 8MP + 2MP",
    cameraTruoc: "20MP",
    loaiCPU: "MediaTek Dimensity 8100 Ultra 8 nhân",
    chipsetVaGPU: "Chipset",
    chip: "Mali G610 MC6",
    congNgheSac: "Sạc nhanh 120W",
    theSim: "2 SIM (Nano-SIM)",
    hoTroMang: "5G",
    wifi: "Wi-Fi 802.11 a/b/g/n/ac/6e, dual-band, Wi-Fi Direct, hotspot",
    bluetooth: "Bluetooth v5.2, A2DP, LE",
    gps: "A-GPS (GLONASS (1), BDS (3), GALILEO (2), QZSS (2), NavIC)",
    kichThuoc: "163.1 x 75.9 x 8.6 mm",
    trongLuong: "202 g",
    chatLieuMatLung: "Kính",
    chatLieuKhungVien: "Kim loại",
}

let sp37 = {
    masp: 37,
    tensp: 'Xiaomi Redmi Note 13 Pro Plus 5G 8GB 256GB',
    tensp1: 'Xiaomi Redmi Note 13 Pro Plus 5G 8GB 256GB',
    tensp2: 'Xiaomi Redmi Note 13 Pro Plus 5G 8GB 256GB',
    hinhanh: '../images/Xiaomi/xiaomi_redmi_note_13_pro_plus_tim_1.png',
    hinhanh1: '../images/Xiaomi/xiaomi_redmi_note_13_pro_plus_tim_2.png',
    hinhanh2: '../images/Xiaomi/xiaomi_redmi_note_13_pro_plus_tim_3.png',
    hinhanh3: '../images/Xiaomi/xiaomi_redmi_note_13_pro_plus_tim_1.png',
    hinhanh4: '../images/Xiaomi/xiaomi_redmi_note_13_pro_plus_tim_2.png',
    hinhanh5: '../images/Xiaomi/xiaomi_redmi_note_13_pro_plus_tim_3.png',
    hinhanh6: '../images/Xiaomi/xiaomi_redmi_note_13_pro_plus_tim-removebg-preview.png',
    soDanhGia: "130 đánh giá",
    loaiPhienBan: "256GB",
    giaHienTai: "10.490.000đ",
    giaHienTai1: "10.490.000đ",
    giaGiam: "10.990.000đ",
    mauSac: 'Tím',
    kichThuocManHinh: '6.67"',
    kichThuocManHinh1: '6.67"',
    congNgheManHinh: "AMOLED",
    congNgheManHinh1: "AMOLED",
    dungLuongRam: "8 GB",
    dungLuongRam1: "8 GB",
    boNhoTrong: "256 GB",
    boNhoTrong1: "256 GB",
    pin: "5000 mAh",
    pin1: "5000 mAh",
    heDieuHanh: "Android 13",
    heDieuHanh1: "Android 13",
    doPhanGiaiManHinh: "1220 x 2712 pixels",
    tanSoQuet: "120Hz",
    kieuManHinh: 'Đục lỗ (Nốt ruồi)',
    cameraSau: "Chính 200 MP & Phụ 8 MP, 2 MP",
    cameraTruoc: "16 MP",
    loaiCPU: "Mediatek Dimensity 7200 Ultra (4 nm)\n2x2.8 GHz Cortex-A715 & 6x2.0 GHz Cortex-A510",
    chipsetVaGPU: "Chipset",
    chip: "Mediatek Dimensity 7200 Ultra (4 nm)",
    congNgheSac: "Sạc nhanh 120W",
    theSim: "2 SIM (Nano-SIM)",
    hoTroMang: "5G",
    wifi: "Wi-Fi MIMO\nWi-Fi Direct\nWi-Fi 802.11 a/b/g/n/ac\nWi-Fi hotspot\nDual-band (2.4 GHz/5 GHz)",
    kichThuoc: "161.4 x 74.2 x 8.9 mm",
    trongLuong: "204.5 g",
    chatLieuKhungVien: "Nhôm",
    chatLieuMatLung: "Kính",
}

let sp38 = {
    masp: 38,
    tensp: 'Xiaomi 13T 12GB 256GB | Chính hãng VN/A',
    tensp1: 'Xiaomi 13T 12GB 256GB | Chính hãng VN/A',
    tensp2: 'Xiaomi 13T 12GB 256GB | Chính hãng VN/A',
    hinhanh: '../images/Xiaomi/xiaomi_13T_xanhDuong_1.png',
    hinhanh1: '../images/Xiaomi/xiaomi_13T_xanhDuong_2.png',
    hinhanh2: '../images/Xiaomi/xiaomi_13T_xanhDuong_3.png',
    hinhanh3: '../images/Xiaomi/xiaomi_13T_xanhDuong_1.png',
    hinhanh4: '../images/Xiaomi/xiaomi_13T_xanhDuong_2.png',
    hinhanh5: '../images/Xiaomi/xiaomi_13T_xanhDuong_3.png',
    hinhanh6: '../images/Xiaomi/xiaomi_13T_xanhDuong-removebg-preview.png',
    soDanhGia: "157 đánh giá",
    loaiPhienBan: "256GB",
    giaHienTai: "12.990.000đ",
    giaHienTai1: "12.990.000đ",
    giaGiam: "11.000.000₫",
    mauSac: 'Xanh dương',
    kichThuocManHinh: '6.67"',
    kichThuocManHinh1: '6.67"',
    congNgheManHinh: "AMOLED",
    congNgheManHinh1: "AMOLED",
    doPhanGiaiManHinh: "1220 x 2712 pixels",
    tanSoQuet: "Từ 144Hz trở lên",
    kieuManHinh: "Kính cường lực Corning Gorilla Glass 5",
    cameraSau: "Camera chính góc rộng: 50 MP, 1/1.22\", f/1,9 | Camera góc siêu rộng: 12 MP, f/2,2 | Camera Tele: 50 MP, f/1,9",
    cameraTruoc: "20 MP, f/2,2",
    loaiCPU: "MediaTek Dimensity 8200-Ultra",
    chipsetVaGPU: "Chipset",
    chip: "1 nhân 3.1 GHz, 3 nhân 3 GHz & 4 nhân 2 GHz | Mali-G610",
    dungLuongRam: "12 GB",
    dungLuongRam1: "12 GB",
    boNhoTrong: "256 GB",
    boNhoTrong1: "256 GB",
    pin: "5.000 mAh",
    pin1: "5.000 mAh",
    heDieuHanh: "Android 13",
    heDieuHanh1: "Android 13",
    wifi: "Wifi 6",
    trongLuong: "197 g (Kính) | 193 g (Da)",
    chatLieuKhungVien: "Kim loại",
    chatLieuMatLung: "Không có thông tin",
    congNgheSac: "Sạc nhanh 67 W",
    theSim: "2 SIM (Nano-SIM)",
    hoTroMang: "5G",
    kichThuoc: "162.2 x 75.7 x 8.49 mm (Kính) | 8.62 mm (Da)",
}

let sp39 = {
    masp: 39,
    tensp: 'Xiaomi Redmi A3 (4GB 128GB) | Chính hãng VN/A',
    tensp1: 'Xiaomi Redmi A3 (4GB 128GB) | Chính hãng VN/A',
    tensp2: 'Xiaomi Redmi A3 (4GB 128GB) | Chính hãng VN/A',
    hinhanh: '../images/Xiaomi/xiaomi_a3_den_1.png',
    hinhanh1: '../images/Xiaomi/xiaomi_a3_den_2.png',
    hinhanh2: '../images/Xiaomi/xiaomi_a3_den_3.png',
    hinhanh3: '../images/Xiaomi/xiaomi_a3_den_1.png',
    hinhanh4: '../images/Xiaomi/xiaomi_a3_den_2.png',
    hinhanh5: '../images/Xiaomi/xiaomi_a3_den_3.png',
    hinhanh6: '../images/Xiaomi/xiaomi_a3_den-removebg-preview.png',
    soDanhGia: "135 đánh giá",
    loaiPhienBan: "128GB",
    giaHienTai: "2.990.000₫",
    giaHienTai1: "2.990.000₫",
    giaGiam: "3.600.000₫",
    mauSac: 'Đen',
    kichThuocManHinh: '6.71"',
    kichThuocManHinh1: '6.71"',
    congNgheManHinh: "Tần số quét 90Hz, 268 ppi, Bảo vệ mắt, 500 nits, Corning® Gorilla® Glass 3",
    congNgheManHinh1: "Tần số quét 90Hz, 268 ppi, Bảo vệ mắt, 500 nits, Corning® Gorilla® Glass 3",
    doPhanGiaiManHinh: "1650x720 pixels",
    tanSoQuet: "90Hz",
    kieuManHinh: "Giọt nước",
    cameraSau: "Camera kép AI 8MP",
    cameraTruoc: "5MP",
    loaiCPU: "MediaTek Helio G36",
    chipsetVaGPU: "Chipset",
    chip: "2.2GHz",
    dungLuongRam: "4 GB",
    dungLuongRam1: "4 GB",
    boNhoTrong: "128 GB",
    boNhoTrong1: "128 GB",
    pin: "5000mAh",
    pin1: "5000mAh",
    heDieuHanh: "Android 14",
    heDieuHanh1: "Android 14",
    wifi: "2.4GHz/5GHz Wi-Fi",
    trongLuong: "199g",
    chatLieuKhungVien: "Không có thông tin",
    chatLieuMatLung: "Không có thông tin",
    congNgheSac: "Sạc nhanh 10W",
    theSim: "2 SIM (Nano-SIM)",
    hoTroMang: "4G",
    kichThuoc: "168.4 x 76.3 x 8.3 mm",
}

let sp40 = {
    masp: 40,
    tensp: 'Xiaomi Redmi Note 12 Pro | Chính hãng VN/A',
    tensp1: 'Xiaomi Redmi Note 12 Pro | Chính hãng VN/A',
    tensp2: 'Xiaomi Redmi Note 12 Pro | Chính hãng VN/A',
    hinhanh: '../images/Xiaomi/Xiaomi_Redmi_Note_12_Pro_5G_tim_1.png',
    hinhanh1: '../images/Xiaomi/Xiaomi_Redmi_Note_12_Pro_5G_tim_2.png',
    hinhanh2: '../images/Xiaomi/Xiaomi_Redmi_Note_12_Pro_5G_tim_3.png',
    hinhanh3: '../images/Xiaomi/Xiaomi_Redmi_Note_12_Pro_5G_tim_1.png',
    hinhanh4: '../images/Xiaomi/Xiaomi_Redmi_Note_12_Pro_5G_tim_2.png',
    hinhanh5: '../images/Xiaomi/Xiaomi_Redmi_Note_12_Pro_5G_tim_3.png',
    hinhanh6: '../images/Xiaomi/Xiaomi_Redmi_Note_12_Pro_5G_tim-removebg-preview.png',
    soDanhGia: "190 đánh giá",
    loaiPhienBan: "128GB",
    giaHienTai: "3.750.000 ₫",
    giaHienTai1: "3.750.000 ₫",
    giaGiam: "6.450.000₫",
    mauSac: 'Tím',
    kichThuocManHinh: '6.67"',
    kichThuocManHinh1: '6.67"',
    congNgheManHinh: "OLED, 1 tỷ màu, 120Hz, Dolby Vision, HDR10+",
    congNgheManHinh1: "OLED, 1 tỷ màu, 120Hz, Dolby Vision, HDR10+",
    doPhanGiaiManHinh: "1080 x 2400 pixels",
    tanSoQuet: "90Hz",
    kieuManHinh: "Giọt nước",
    cameraSau: "50 MP, f/1.9, 24mm (góc rộng), PDAF, OIS | 8 MP, f/1.9, 119˚ (góc siêu rộng) | 2 MP, f/2.4, (macro)",
    cameraTruoc: "16 MP (góc rộng)",
    loaiCPU: "MediaTek Dimensity 1080 (6nm)",
    chipsetVaGPU: "Chipset",
    chip: "8 nhân (2x2.6 GHz & 6x2.0 GHz) | GPU: Mali-G68 MC4",
    dungLuongRam: "6-12GB",
    dungLuongRam1: "6-12GB",
    boNhoTrong: "128-256GB",
    boNhoTrong1: "128-256GB",
    pin: "Li-Po 5000mAh",
    pin1: "Li-Po 5000mAh",
    heDieuHanh: "Android 12, MIUI 13",
    heDieuHanh1: "Android 12, MIUI 13",
    wifi: "Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct, hotspot",
    trongLuong: "187 g",
    chatLieuKhungVien: "Không có thông tin",
    chatLieuMatLung: "Không có thông tin",
    congNgheSac: "Sạc nhanh 67W, 100% trong 46 phút (quảng cáo)",
    theSim: "2 SIM, Nano SIM",
    hoTroMang: "4G",
    kichThuoc: "162.9 x 76 x 7.9 mm",
}

let dsIphone = [sp1, sp2, sp3, sp4, sp5, sp6, sp7, sp8, sp9, sp10]
localStorage.setItem("dsIphone", JSON.stringify(dsIphone))

let dsSamsung = [sp11, sp12, sp13, sp14, sp15, sp16, sp17, sp18, sp19, sp20]
localStorage.setItem("dsSamsung", JSON.stringify(dsSamsung))

let dsOppo = [sp21, sp22, sp23, sp24, sp25, sp26, sp27, sp28, sp29, sp30]
localStorage.setItem("dsOppo", JSON.stringify(dsOppo))


let dsXiaomi = [sp31, sp32, sp33, sp34, sp35, sp36, sp37, sp38, sp39, sp40]
localStorage.setItem("dsXiaomi", JSON.stringify(dsXiaomi))

let dssp = [sp1, sp2, sp3, sp4, sp5, sp6, sp7, sp8, sp9, sp10, sp11, sp12, sp13, sp14, sp15, sp16, sp17, sp18, sp19, sp20, sp21, sp22, sp23, sp24, sp25, sp26, sp27, sp28, sp29, sp30, sp31, sp32, sp33, sp34, sp35, sp36, sp37, sp38, sp39, sp40]
localStorage.setItem("dssp", JSON.stringify(dssp))